# -*- coding: utf-8 -*-
import re
steps = {
"pakistan": '"Kuzu etini yoğurt, zencefil-sarımsak ezmesi, garam masala, acı biber ve tuzla marine edip 2 saat bekletin.","Basmati pirincini 30 dakika ıslatıp süzün. Kaynar tuzlu suda 5 dakika, yarı pişene kadar haşlayıp süzün.","Geniş tencerede ghee ile soğanları koyu kahverengiye kadar 20 dakika kavurun. Marine edilmiş eti ekleyip 15 dakika kavurun.","Tencereye sırasıyla: et, yarı pişmiş pirinç, kızarmış soğan, nane, kişniş ve safranlı sütü katlar halinde dizin.","Kapağı hamurla veya folyo ile mühürleyin. En kısık ateşte 40 dakika dum pişirin — kapağı hiç açmayın.","Servis ederken katları nazikçe karıştırın. Kızarmış soğan ve taze nane ile süsleyip sıcak servis edin."',
"bangladesh": '"Ilısa balığı dilimlerini zerdeçal ve tuzla ovup 15 dakika bekletin.","Hardal tohumlarını 2 yemek kaşığı su ile blenderda pürüzsüz bir macun haline getirin.","Tavada hardal yağını orta ateşte kızdırın. Balık dilimlerini her iki tarafı 2 dakika olmak üzere hafifçe kızartıp çıkarın.","Aynı tavada yeşilbiberleri 1 dakika kavurun. Hardal macununu, 1/2 çay kaşığı zerdeçal ve 100ml su ekleyin.","Sos kaynamaya başlayınca balık dilimlerini nazikçe yerleştirin. Kısık ateşte 8-10 dakika, sos koyulaşana kadar pişirin.","Sıcak beyaz pirinç pilavı üzerine balıkları sosla birlikte düzgünce yerleştirerek servis edin."',
"nepal": '"Hamur için unu, suyu ve tuzu karıştırıp 10 dakika pürüzsüz olana kadar yoğurun. Islak bezle örtüp 30 dakika dinlendirin.","Kıymayı ince kıyılmış soğan, sarımsak, zencefil, kişniş, tuz ve karabiberle yoğurun.","Hamuru küçük toplar yapıp oklavayla 8cm çapında ince daireler açın.","Her dairenin ortasına 1 tatlı kaşığı harç koyun. Kenarlarını yukarı kaldırıp kıvırarak üstü kapalı kesecik şekli verin — en üstte küçük bir açıklık bırakın.","Buharlı tencereye (bambu sepet veya metal süzgeç) yağlanmış kağıt serin. Momoları aralarında boşluk bırakarak dizin. Kapağı kapatıp 12-15 dakika buharda pişirin.","Soya sosu, sirke ve acı biberden yapılan dip sosla sıcak servis edin."',
"sri_lanka": '"Pirinci yıkayıp hindistancevizi sütü ve 1 su bardağı su ile tencereye koyun. Köri yaprağı ve zerdeçali ekleyin. Kaynayınca kısık ateşte 18 dakika pişirin.","Dhal: Mercimeği 400ml su ile 20 dakika yumuşayana kadar haşlayın. Hindistancevizi sütü, zerdeçal ve tuz ekleyip 5 dakika daha pişirin.","Ayrı tavada soğan, sarımsak ve köri yapraklarını 5 dakika kavurun. Köri tozu ekleyip 1 dakika karıştırın.","Sebzeleri (patates, fasulye) bu karışıma ekleyip 200ml su ile yumuşayana kadar 15-20 dakika pişirin.","Pol sambol: Rendelenmiş hindistancevizini soğan, biber, limon suyu ve tuzla karıştırın.","Geniş tabağa pirinçi ortaya koyun. Etrafına dhal, sebze körisi, pol sambol ve pappadam dizin."',
"myanmar": '"Balığı temizleyip parçalara ayırın. Tencerede 1L su ile 15 dakika haşlayın. Balığı çıkarıp didikleyin, suyu saklayın.","Soğan, sarımsak, zencefil ve zerdeçali yağda 8 dakika, soğanlar yumuşayana kadar kavurun.","Limon otunu ezip macunla birlikte kavurmaya ekleyin. 2 dakika karıştırın.","Balık suyunu ekleyip kaynattın. Nohut ununu soğuk suyla açıp çorbanın içine yavaş yavaş dökerek koyulaştırın.","Didiklenmiş balığı ekleyip 10 dakika kısık ateşte pişirin. Balık sosu ve tuzla tadını ayarlayın.","Pirinç noodle\'ları haşlayıp kaselere bölün. Çorbayı üzerine dökün. Kızarmış soğan, kişniş, limon dilimi ve acı biber yağı ile servis edin."',
"cuba": '"Bifteği 1.5L su ile tencereye koyun. Kaynayınca köpüğü alıp kısık ateşte 1.5-2 saat, çatalla kolayca ayrılacak kadar yumuşayana dek haşlayın.","Eti çıkarıp 10 dakika soğumaya bırakın. İki çatalla lifleri boyunca ince ince didikleyin.","Geniş tavada zeytinyağını kızdırın. Soğan ve biber jülyenlerini 8 dakika, yumuşayana dek kavurun. Sarımsağı ekleyip 1 dakika daha.","Domates püresi, kimyon ve defne yaprağını ekleyip 10 dakika kaynatın. Sos koyulaşmalı.","Didiklenmiş eti sosa katıp 15 dakika kısık ateşte, et tüm sosları emene kadar karıştırarak pişirin. Tuz ayarı yapın.","Beyaz pirinç pilavı, kızarmış muz dilimleri ve siyah fasulye eşliğinde servis edin."',
"jamaica": '"Jerk sosu: Scotch bonnet biberleri, yenibahar, kekik, sarımsak, zencefil, soya sosu ve limon suyunu blenderda pürüzsüz bir macun haline getirin.","Tavuk butlarına derin çizikler atın (kemiğe kadar). Jerk macununu eldiven giyerek her tarafa iyice ovun.","Marine edilmiş tavuğu streç filmle kapatıp buzdolabında en az 4 saat, ideal olarak bir gece bekletin.","Izgarayı veya fırını 180°C\'ye hazırlayın. Tavukları dolaylı ısıda, kapağı kapalı olarak 35-40 dakika, iç sıcaklık 75°C olana kadar yavaş pişirin.","Son 5 dakikada direkt ateşe yaklaştırıp deri tarafını çıtırlaştırın. Yanmamaya dikkat edin — jerk\'ün acı biberleri çabuk yanar.","Tahtada 5 dakika dinlendirip parçalayın. Yanında pirinç-bezelye pilavı, kızarmış muz ve coleslaw ile servis edin."',
"dominican": '"Pirinci yıkayıp 2 yemek kaşığı yağda 2 dakika kavurun. 2 kat su ve tuz ekleyip kısık ateşte 20 dakika pişirin.","Fasulyeleri soğan, sarımsak, biber ve zeytinyağıyla 20 dakika, sos koyulaşana kadar pişirin.","Tavuğu tuz, limon, sarımsak ve oregano ile marine edip tavada her tarafı 5 dakika çevirerek kızartın. 200ml su ekleyip kapağı kapatarak 25 dakika daha pişirin.","Olgun muzları boyuna ikiye kesin, tereyağlı tavada her iki tarafı altın rengine gelene kadar 2 dakika kızartın.","Yeşil salatayı domates, soğan ve limon-zeytinyağı sosuyla hazırlayın.","Büyük tabağa pirinç, fasulye, tavuk, kızarmış muz ve salata yan yana dizin — Dominik bayrağı gibi renkli bir tabak oluşturun."',
"venezuela": '"Mısır ununu ılık tuzlu suyla karıştırın. 3 dakika yoğurup hamur toparlanana kadar dinlendirin.","Hamurdan avuç içinden büyük toplar alıp 1.5cm kalınlığında, 10cm çapında diskler şekillendirin. Kenarları pürüzsüz olsun.","Yapışmaz tavada veya ızgarada orta ateşte her iki tarafı 5-6 dakika, dışı çıtır kabuk bağlayana kadar pişirin.","Fırını 190°C\'ye ısıtıp arepaları 15 dakika daha fırınlayın — şişip hafifleşecekler. Yanlarına vurduğunuzda boş ses gelmeli.","Arepaları ortadan yatay olarak kesin (tamamen ayırmayın). İç kısmını kaşıkla biraz oyun.","İçine ufalanmış beyaz peynir, avokado dilimleri, siyah fasulye veya çekilmiş et doldurun. Sıcak servis edin."',
"chile": '"Hamur: Unu tereyağıyla ovalayarak kum gibi bir kıvam alana kadar karıştırın. Yumurta ve soğuk su ekleyip hamuru toplayın. Streç filmle sarıp 30 dakika buzdolabında dinlendirin.","İç harç: Soğanları küp doğrayıp 8 dakika kavurun. Kıymayı ekleyip 10 dakika parçalayarak pişirin. Kimyon, tuz ve biber ekleyin.","Harcı ateşten alıp soğumaya bırakın. Zeytin ve haşlanmış yumurta dilimlerini karıştırın.","Hamuru 3mm kalınlığında açıp 15cm çapında daireler kesin. Ortaya 2 yemek kaşığı harç koyun.","Kenarları katlayıp çatalla bastırarak mühürleyin. Üstüne yumurta sarısı sürün.","200°C fırında 25-30 dakika, altın sarısı olana kadar pişirin. Sıcak veya oda sıcaklığında servis edin."',
"ecuador": '"Ton balığını büyük parçalar halinde kesin. Tuzlu kaynayan suda 15 dakika haşlayın. Çıkarıp büyük parçalara ayırın.","Manyoku soyup 3cm küpler halinde kesin. Kaynar tuzlu suda 15-20 dakika, çatala kolayca girene kadar haşlayın.","Tencerede soğan halkalarını zeytinyağında 5 dakika kavurun. Domatesleri ve kimyonu ekleyip 5 dakika pişirin.","1L su veya balık suyunu ekleyip kaynattın. Haşlanmış manyoku ve balığı nazikçe yerleştirin.","Kısık ateşte 10 dakika birlikte pişirin. Limon suyu, tuz ve karabiber ile tadını ayarlayın.","Derin kaselere paylaştırın. Üzerine kıyılmış kişniş serpin, yanında ekstra limon dilimleri ve patacones (kızarmış yeşil muz) ile servis edin."',
"bolivia": '"Hamuru un, tereyağı, yumurta ve tuzla yoğurun. 30 dakika buzdolabında dinlendirin.","İç harç: Kıymayı soğan, patates küpleri ve bezelyeyle 15 dakika kavurun. Jelatin, et suyu ve baharat ekleyip soğutun — karışım jöle gibi katılaşmalı.","Hamuru ince açıp 12cm daireler kesin. Ortaya 2 yemek kaşığı soğuk harç ve haşlanmış yumurta dilimi koyun.","Kenarlarını repulgue (örgü) tekniğiyle kapatın — bu hem süsler hem sızıntıyı önler.","Üstüne yumurta sürün. 200°C fırında 25-30 dakika, altın sarısı olana kadar pişirin.","Dikkatli yiyin — içindeki jöleli sos sıcakken sıvıdır ve ağzınızı yakabilir. Yanında acı sos ile servis edin."',
"uruguay": '"Bifteği parmaklar arasında ince hissedilene kadar et tokmağıyla dövün. Tuz ve karabiber serpin.","Kızgın ızgarada veya döküm tavada her iki tarafı 3 dakika pişirin — içi pembemsi kalmalı.","Sandviç ekmeğini ortadan kesip iç yüzlerini 30 saniye ızgarada kızartın.","Alt ekmeğe mayonez sürün, marul, domates dilimleri koyun. Üzerine sıcak bifteği yerleştirin.","Bifteğin üstüne jambon, mozzarella ve sahanda yumurta koyun. Zeytinleri yerleştirin.","Üst ekmeği kapatıp köşeden köşeye kesip çıtır patates kızartmasıyla birlikte servis edin."',
}
with open("Models/CountryData.swift") as f:
    content = f.read()
updated = 0
for cid, new_steps in steps.items():
    pattern = rf'(id: "{cid}".*?steps: \[)\s*\n\s*[^\]]*(\])'
    def replacer(m, ns=new_steps):
        return m.group(1) + "\n                " + ns + "\n            " + m.group(2)
    new_content = re.sub(pattern, replacer, content, flags=re.DOTALL, count=1)
    if new_content != content:
        updated += 1
        content = new_content
with open("Models/CountryData.swift", "w") as f:
    f.write(content)
print(f"Batch 3: Updated {updated} countries")
