# -*- coding: utf-8 -*-
import re
steps = {
"croatia": '"Mürekkep balığını temizleyip halka kesin. Mürekkep torbalarını ayırıp bir kenara koyun.","Tencerede zeytinyağıyla soğanı 5 dakika kavurun. Balık halkalarını ekleyip 3 dakika soteleyin.","Beyaz şarabı ekleyip 2 dakika buharlaştırın. Arborio pirincini ekleyip 1 dakika yağla kaplayacak şekilde kavurun.","Sıcak balık suyunu kepçe kepçe ekleyin. Her kepçe emildikten sonra bir sonrakini ekleyin. 18-20 dakika sürekli karıştırın.","Son kepçeyle birlikte mürekkep torbalarını sıkıp sosumu ekleyin — risotto simsiyah olacak. Parmesan ve tereyağı ekleyin.","Tabağa yayıp birkaç damla zeytinyağı gezdirin. İsteğe göre maydanoz yaprağı ile süsleyerek servis edin."',
"bosnia": '"Yufkayı ince açın veya hazır yufka kullanın. Her yufka yaprağını tezgaha serin.","Kıyma harcı: Kıymayı soğan, tuz, karabiber ile yoğurun. Peynirli yapacaksanız peyniri ufalayın.","Yufkanın alt kenarı boyunca ince bir şerit halinde harç yayın. Alt kenarı katlayıp sıkıca silindir gibi sarın.","Sarılmış börekleri yuvarlak fırın tepsisine salyangoz şeklinde kıvrılarak dizin — ortadan başlayıp dışa doğru sarmal yapın.","Üzerine fırçayla yağ ve yumurta karışımı sürün. 180°C fırında 35-40 dakika, altın sarısı olana kadar pişirin.","10 dakika dinlendirip dilimleyin. Yanında soğuk yoğurt ile sıcak servis edin."',
"albania": '"Tavuk parçalarını tuz ve karabiberle ovun. Tavada zeytinyağıyla her tarafı 3-4 dakika mühürleyin.","Pirinci yıkayıp süzün. Tereyağında 2 dakika kavurup 2 kat su ile kısık ateşte 15 dakika pişirin.","Yoğurt sosunu hazırlayın: Yoğurdu yumurta, un ve ezilmiş sarımsakla pürüzsüz olana kadar çırpın.","Yağlanmış fırın kabının tabanına pilav yayın. Üstüne tavuk parçalarını dizin.","Yoğurt karışımını tavuk ve pilavın üzerine eşit şekilde dökün.","180°C fırında 45-50 dakika, üstü altın sarısı ve kabarcıklı olana kadar pişirin. 10 dakika dinlendirip servis edin."',
"georgia_country": '"Hamur: Unu, yoğurdu, tuzu ve kabartma tozunu karıştırıp 5 dakika yoğurun. Islak bezle örtüp 20 dakika dinlendirin.","Peyniri rendeleyip bir kasede karıştırın. 2 peynir arışımı (sülügüni + taze peynir) en iyi sonucu verir.","Hamuru 4 parçaya bölün. Her parçayı oval/kayık şeklinde açın (30cm uzunluğunda). Kenarları yukarı katlayıp sıkıştırarak kayık bordası oluşturun.","Her kayığın ortasına bol peynir doldurun. Uçları sivrilterek kapatın — merkez açık kalmalı.","200°C fırında 12-15 dakika, hamur kızarıp peynir eriyene kadar pişirin.","Fırından çıkarınca hemen ortasına çiğ yumurta kırın ve 1 parça tereyağı koyun. Yumurta beyazı pişerken sarısı akıcı kalmalı — çatal ile karıştırarak sıcak sıcak yiyin."',
"armenia": '"Hamuru un, su, tuz ve zeytinyağı ile yoğurup 30 dakika dinlendirin. Toplar yapıp çok ince (2mm) açın.","Kıyma harcı: Kıymayı rendelenmiş domates, ince kıyılmış soğan, biber, maydanoz ve pul biberle karıştırın. Sos gibi akıcı olmalı.","İnce açılmış hamurların üzerine harcı 3mm kalınlığında eşit şekilde yayın — hamur görünmemeli.","250°C\'ye ısıtılmış fırında 6-8 dakika, kenarları kıvrılıp hafif yanık lekeler oluşana kadar pişirin.","Fırından çıkarınca üzerine taze limon suyu sıkın. Maydanoz ve ince doğranmış soğan serpin.","Düz olarak yiyebilir veya rulo şeklinde sarıp marul ve limonla birlikte yiyebilirsiniz."',
"azerbaijan": '"Pirinci soğuk suda 3 kez yıkayıp 1 saat ıslatın, süzün.","Kuzu etini küp doğrayıp tuz, karabiber ve kimyonla marine edin. Tencerede yağda her tarafı mühürleyin. Su ekleyip 40 dakika pişirin.","Kaynar tuzlu suda pirinci 5-6 dakika, yarı pişene kadar haşlayın. Süzün.","Tencerenin dibine tereyağı ve 2 yemek kaşığı su koyun. Pirincin bir kısmını yayın. Safranı sıcak suda eritip pirinçe dökün.","Kuru kayısı, kuru üzüm ve kestaneleri pirinç katmanı arasına serpin. Kalan pirinci üstüne yığın.","Kapağı havlu ile sarıp (buhar emsin) en kısık ateşte 45 dakika, taban çıtır olana kadar pişirin. Ters çevirip et ile servis edin."',
"uzbekistan": '"Geniş kalın tabanlı kazanı (veya döküm tencereyi) yüksek ateşte kızdırın. Yağı ekleyip dumanı çıkana kadar ısıyın.","Büyük parça kuzu etini kazana koyup her tarafı koyu kahverengiye kadar 5-6 dakika mühürleyin. Çıkarın.","Soğan halkalarını 5 dakika kavurup kalın jülyen havuçları ekleyin. 10 dakika, havuçlar yumuşayana kadar soteleyin.","Eti geri koyun. Kimyon, tuz ve karabiber serpin. Nemlenmemiş nohutları ve bütün sarımsak başını ekleyin.","Sıcak su ekleyip kaynattın. Yıkanmış pirinci eşit şekilde üste dökün ama karıştırmayın. Kapağı sıkıca kapatın.","Kısık ateşte 25-30 dakika, pirinç suyunu çekene kadar pişirin. Sarımsağı çıkarıp büyük tabağa ters çevirerek servis edin."',
"kazakhstan": '"Büyük parça eti geniş tencereye koyup soğuk su ile başlayarak kaynattın. Köpüğü alarak kısık ateşte 2-2.5 saat, et yumuşayana kadar haşlayın.","Taze yufka hamurunu hazırlayın veya hazır yufka kullanın. Geniş şeritler (5x10cm) halinde kesin.","Soğan halkalarını et suyundan 3 kepçe ile tencerede 10 dakika, yumuşayana kadar soteleyin.","Yufka şeritlerini kaynayan tuzlu et suyunda 3-4 dakika haşlayın. Süzün.","Eti kemiklerinden ayırıp büyük parçalara bölün.","Büyük tabağa önce yufkayı yayın, üzerine eti dizin, soğanları dağıtın ve 1-2 kepçe et suyu gezdirin. Geleneksel olarak elle yenir."',
"mongolia": '"Hamuru un, su ve tuzla yoğurup 20 dakika dinlendirin.","Koyun kıymayı ince kıyılmış soğan, sarımsak, kimyon, tuz ve karabiber ile yoğurun.","Hamuru golf topu büyüklüğünde parçalara bölün. Her birini 10cm çapında daireler halinde açın.","Ortaya 1 yemek kaşığı harç koyun. Hamuru yarım daire katlayıp kenarları sıkıca kapatın, üst kısmı açık bırakarak rozet şekli verin.","Buharlı tencereye yağlanmış kağıt serip buuzları aralıklı dizin. Kapağı kapatıp 15-18 dakika buharda pişirin.","Sıcak servis edin — ilk ısırıkta dikkatli olun, içindeki sıvı et suyu çok sıcak olabilir."',
"saudi": '"Tavuğu veya kuzu etini büyük parçalar halinde tencereye koyun. Kabsa baharatı, tuz ve su ekleyip 30-40 dakika haşlayın.","Eti çıkarıp fırın ızgarası altında veya tavada her tarafı çıtır olana kadar 5 dakika kızartın.","Aynı tencerede soğan ve sarımsağı 5 dakika kavurun. Rendelenmiş domatesleri ekleyip 8 dakika pişirin.","Yıkanmış pirinci ekleyin. Et suyunu ve baharatları katın. Kaynayınca kısık ateşte 18-20 dakika pişirin.","Limon dilimlerini pilavın üstüne dizin. Kapağı kapatıp 5 dakika dinlendirin.","Büyük tabağa pilavı yığın, üstüne çıtır eti yerleştirin. Kavrulmuş badem ve kuru üzümle süsleyerek servis edin."',
"uae": '"Tavuğu bütün olarak bezar baharatı, zerdeçal, tuz ve su ile tencerede 30 dakika haşlayın. Çıkarıp tavuk suyunu saklayın.","Geniş tencerede ghee ile soğanları koyu kahverengiye kadar 15 dakika kavurun. Domatesleri ekleyip 5 dakika pişirin.","Yıkanmış basmati pirincini ekleyip 1 dakika kavurun. Saklanan tavuk suyunu ve limon suyunu ekleyin.","Kaynayınca kısık ateşte 15-18 dakika pişirin. Son dakikada gül suyunu ekleyin.","Haşlanmış tavuğu fırında veya tavada çıtırlaştırın.","Pilavı tabağa yığıp üstüne tavuk yerleştirin. Kızarmış soğan ve taze kişniş ile süsleyin."',
"jordan": '"Jameed yoğurdunu ılık suda 6-8 saat ıslatıp blenderdan geçirerek pürüzsüz bir sıvı haline getirin.","Kuzu etini tencereye koyup su ile 1.5 saat, et yumuşayana kadar haşlayın.","Hazırlanan jameed sıvısını et suyuyla karıştırarak tencereye dökün. Baharatları ekleyip 30 dakika kısık ateşte kaynatın — sürekli karıştırın yoksa kesilir.","Pirinci ayrı tencerede tereyağıyla kavurup 2 kat su ile 18 dakika pişirin.","Badem ve çam fıstıklarını tereyağında altın rengine gelene kadar kavurun.","Büyük yuvarlak tabağa önce lavaş ekmeği yayın, üstüne pilav, ardından kuzu parçalarını dizin. Jameed sosunu bolca gezdirip kavrulmuş kuruyemişleri serpin."',
"iraq": '"Balığı boyunca ikiye ayırıp kılçıkları temizleyin. İç kısmına zerdeçal, tuz ve tamarind ezmesi sürün.","Odun ateşi yakıp kor haline gelmesini bekleyin. Uzun şişlere balık yarımlarını takıp ateşin yanına dikey şekilde sabitleyin.","Dolaylı ısıyla 30-40 dakika yavaş yavaş pişirin. Balığın etine baktığınızda beyazlaşmış ve kolayca sıyrılıyor olmalı.","Son 10 dakikada dilimlenmiş domates ve soğanları balığın üzerine dizin. Ateşin ısısıyla hafifçe pişmelerini sağlayın.","Balığı şişlerden dikkatli çıkarıp büyük tabağa yerleştirin.","Üzerine taze limon sıkıp domates-soğan garnitürü ile birlikte sıcak pirinç pilavı eşliğinde servis edin."',
"syria": '"Dış hamur: İnce bulguru yıkayıp 15 dakika ıslatın. Süzüp kıyma, ince rendelenmiş soğan, yedi baharat, tarçın ve tuzla 10 dakika yoğurun — pürüzsüz ve yapışkan olmalı.","İç harç: Ayrı tavada kıymayı soğanla 8 dakika kavurun. Çam fıstığı, baharat ekleyin. Soğumaya bırakın.","Ellerinizi ıslatarak dış hamurdan ceviz büyüklüğünde top alın. Başparmağınızla ortasını oyup ince çanaklı bir şekil verin.","Çanağın içine 1 çay kaşığı iç harç koyun. Açıklığı kapatıp sivri uçlu rugby topu şekli verin.","Yağı 170°C\'ye kadar kızdırın. Kibbeleri 4-5 dakika, her tarafı altın kahverengisi olana kadar kızartın. Kağıt havluda süzün.","Sıcak veya ılık olarak limon dilimleri ve yeşil salata ile servis edin."',
"israel": '"Nohutları soğuk suda bir gece ıslatın. Ertesi gün süzün — kesinlikle haşlamayın, çiğ nohutla yapılır.","Nohutları mutfak robotuna alın. Maydanoz, kişniş, soğan, sarımsağı ve kimyonu ekleyin. Kısa aralıklarla (pulse) iri kum kıvamına gelene kadar çekin — pürüzsüz yaparsanız falafel dağılır.","Harça tuzu ve unu ekleyin. Son birkaç pulse ile karıştırın. Harcı streç filmle kapatıp 1 saat buzdolabında dinlendirin.","Islak ellerle ceviz büyüklüğünde toplar yuvarlayıp hafifçe yassılaştırın — 3cm çapında, 2cm kalınlığında olmalı.","Yağı 175°C\'ye kızdırın. Falafelleri 3-4 dakika, dışı koyu altın sarısı ve çıtır olana kadar kızartın. Kağıt havluda süzün.","Pide ekmeğinin içine marul, domates, turşu ve tahin sosu koyun. Sıcak falafelleri yerleştirip hemen servis edin."',
}
with open("Models/CountryData.swift") as f:
    content = f.read()
updated = 0
for cid, new_steps in steps.items():
    pattern = rf'(id: "{cid}".*?steps: \[)\s*\n\s*[^\]]*(\])'
    def replacer(m, ns=new_steps):
        return m.group(1) + "\n                " + ns + "\n            " + m.group(2)
    new_content = re.sub(pattern, replacer, content, flags=re.DOTALL, count=1)
    if new_content != content:
        updated += 1
        content = new_content
with open("Models/CountryData.swift", "w") as f:
    f.write(content)
print(f"Batch 5: Updated {updated} countries")
