# -*- coding: utf-8 -*-
import re
steps = {
"paraguay": '"Soğanları küp doğrayıp tereyağında 8 dakika, yumuşayıp pembeleşene kadar kavurun. Soğumaya bırakın.","Geniş kapta yumurtaları süt ve eritilmiş tereyağıyla çırpın. Mısır ununu ve tuzu ekleyerek pürüzsüz bir hamur haline getirin.","Kavrulmuş soğanları ve rendelenmiş peynirin 3/4\'ünü hamura katıp karıştırın.","Yağlanmış ve unlanmış fırın kalıbına hamuru dökün. Yüzeyi düzleştirip kalan peyniri üzerine serpin.","180°C önceden ısıtılmış fırında 40-45 dakika, üstü altın sarısı olana ve bıçağa hamur yapışmayacak kadar pişirin.","10 dakika kalıpta dinlendirip dilimleyin. Sıcak veya oda sıcaklığında, yanında et yemeği ile servis edin."',
"costa_rica": '"Önceki günden pişirilmiş pirinç ve siyah fasulyeleri buzdolabından çıkarıp oda sıcaklığına getirin.","Geniş tavada yağı kızdırıp soğan ve biberi 5 dakika kavurun. Fasulyeleri ekleyip çatalla hafifçe ezerek 3 dakika pişirin.","Soğuk pirinci ekleyin. Salsa Lizano\'yu gezdirin. Orta ateşte sürekli karıştırarak 5-7 dakika, pirinç ısınıp baharatları emene kadar pişirin.","İsteğe göre pirincin bir kısmının tavada çıtır kabuk bağlamasını sağlayın — karıştırmadan 2 dakika bırakın.","Taze kişnişi ince kıyıp pilavın üzerine serpin. Tuz ve biber ayarını yapın.","Tabağa sahanda yumurta, olgun muz dilimleri, ekşi krema ve taze avokado eşliğinde servis edin."',
"panama": '"Tavuğu soğuk su ile yıkayıp geniş ve derin tencereye koyun. Üzerini geçecek kadar su ekleyin. Kaynayınca köpüğü alın.","Soğan, sarımsak ve oreganoyu ekleyin. Kısık ateşte 30 dakika pişirin.","Manyok ve mısır parçalarını ekleyip 20 dakika daha, manyok yumuşayana kadar pişirin.","Taze kişnişi saplarıyla birlikte tencereye atıp son 5 dakika kaynatın. Tuz ve biber ile tadını ayarlayın.","Tavuğu çıkarıp parçalara ayırın. Kemikleri çıkarın.","Derin kaselere çorba suyunu, sebzeleri ve tavuk parçalarını paylaştırın. Taze kışniş serpin ve limon dilimiyle servis edin."',
"iceland": '"Tuzlu balığı 24 saat soğuk suda ıslatıp tuzunu giderin. Her 8 saatte suyu değiştirin.","Patatesleri soyup küçük parçalar halinde kesin. Kaynar tuzlu suda 15-18 dakika, çatala kolayca girene kadar haşlayın.","Tuzdan arınmış balığı kaynar suya atıp 10 dakika haşlayın. Çıkarıp derisi ve kılçığını temizleyip parçalara ayırın.","Geniş tavada tereyağını eritip soğanı 5 dakika, yumuşayana kadar kavurun.","Haşlanmış patatesleri, balığı ve kavrulmuş soğanı tencereye alın. Sütü ekleyip çatalla kabaca ezin — tamamen pürüzsüz değil, parçacıklı olmalı. Karabiber serpin.","Sıcak olarak çavdar ekmeği dilimleri ve turşu ile servis edin."',
"ireland": '"Kuzu etini geniş tencerede 2 yemek kaşığı yağda yüksek ateşte her tarafı kahverengileşene kadar 5-6 dakika mühürleyin. Çıkarın.","Aynı tencerede soğanları 5 dakika kavurun. Et suyunu ekleyip tencere dibindeki lezzetleri çözün.","Eti tencereye geri koyun. Havuç ve kekik ekleyin. Kaynayınca kısık ateşe getirin.","Patates dilimlerini en üste tek sıra dizin — buhar alarak piştirirken yahninin kapağı görevini görürler.","Kapağı kapatıp 1.5-2 saat, et çatalla ayrılacak kadar yumuşayana dek kısık ateşte pişirin.","Taze maydanoz serpin. Tencereden doğrudan kaselere bölüp çıtır ekmek ile servis edin."',
"netherlands": '"Patatesleri soyup dörde bölün. Kaynar tuzlu suda 18-20 dakika, çatala kolayca girene kadar haşlayın.","Lahana yapraklarını yıkayıp ince şeritler halinde kesin. Son 5 dakikada patateslerin üstüne ekleyip birlikte haşlayın.","Süzüp tencereye geri alın. Tereyağı ve sıcak sütü ekleyin. Patates ezme aleti ile iyice ezin — pürüzsüz değil, biraz dokulu olmalı.","Hardal, tuz ve karabiberi ekleyip karıştırın.","Rookworst sosisini kaynar suda 15 dakika ısıtın (zaten pişmiştir, sadece ısıtılır).","Stamppotu tabağa yığın, çukur açıp içine jus (et sosu) dökün. Yanında Rookworst sosisi ve ekstra hardal ile servis edin."',
"belgium": '"Midyeleri soğuk suda bir bir kontrol edin. Açık olanları masaya sert vurun — kapanmazsa atın. Sakal ipliklerini koparıp fırçayla temizleyin.","Geniş ve derin tencerede tereyağını eritin. Soğan ve sarımsağı 5 dakika, yumuşayana kadar kavurun.","Beyaz şarabı ekleyip 2 dakika kaynatın. Midyeleri tencereye dökün, kapağı sıkıca kapatın.","Yüksek ateşte 4-5 dakika, tüm midyeler açılana kadar ara sıra tencereyi sallayarak pişirin. Açılmayan midyeleri atın.","Kremayı ekleyip 1 dakika daha kaynatın. Bol maydanoz serpin.","Patatesleri 2 kez kızartma yöntemiyle (150°C, sonra 190°C) hazırlayın. Midyeleri tencereyle masaya getirip yanında patates kızartması ve extra mayonez ile servis edin."',
"switzerland": '"Fondu kabının iç yüzeyini kesik sarımsak dişiyle iyice ovun — kabın her yerine sarımsak aroması sinmeli.","Peyniri ince rendeleyin. Mısır nişastasıyla karıştırarak unlayın — bu peynirin topaklı erimesini önler.","Fondu kabını ocağa koyup beyaz şarabı ekleyin. Orta ateşte şarap hafifçe kaynamaya başlayınca avuç avuç peynir eklemeye başlayın.","Her avuç peyniri sürekli 8 şeklinde karıştırarak tamamen eritin, sonra bir sonrakini ekleyin. Tümü eriyene kadar 10-12 dakika devam edin.","Kiraz likörünü ekleyip karıştırın. Fondu kabını alkolün arkasından taşınabilir brülöre (rechaud) koyun — sıcak tutması yeterli, kaynatmamalı.","Çıtır ekmek küplerini uzun çatallara takıp fondüye daldırarak yiyin. Ekmek düşerse geleneğe göre masaya bir şişe şarap ısmarlarsınız!"',
"austria": '"Dana etini parmaklar kalınlığını zor hissedene kadar et tokmağıyla streç film arasında çok ince (3-4mm) dövün.","3 tabak hazırlayın: un (tuzlu), çırpılmış yumurta, galeta unu. Eti sırasıyla una, yumurtaya ve galeta ununa bulayın — kaplamanın gevşek durmasına dikkat edin, bastırarak yapıştırmayın.","Geniş tavada (kesinlikle derin kızartma değil) bol tereyağını orta-yüksek ateşte eritin. Tereyağı köpürüp köpüğü azaldığında hazırdır.","Kaplı eti yavaşça tavaya bırakın. Tavayı hafifçe sallayarak kaplama altında hava yastığı oluşmasını sağlayın — bu schnitzel\'in kabarık ve dalgalı görünümünü verir.","Her tarafı 2-3 dakika, altın sarısı olana kadar kızartın. Kağıt havluda fazla yağını alın.","Tabağa koyup taze sıkılmış limon dilimi ve maydanoz yaprağı ile süsleyin. Patates salatası veya salata ile servis edin."',
"poland": '"Hamur: Unu tezgaha yığın, ortasına çukur açın. Yumurta ve ılık suyu ekleyip 10 dakika pürüzsüz ve elastik olana kadar yoğurun. Islak bezle örtüp 30 dakika dinlendirin.","İç: Haşlanmış patatesleri iyice ezin. Kavrulmuş soğanı ve ufalanmış peyniri ekleyip karıştırın. Tuz ve biberle tatlandırın.","Hamuru unlı tezgahta 2-3mm kalınlığında açın. 8cm çapında daireler kesin (bardak kullanabilirsiniz).","Her dairenin ortasına 1 yemek kaşığı harç koyun. İkiye katlayıp kenarları çatalla bastırarak sıkıca mühürleyin.","Tuzlu kaynayan suda 5-6 tane olacak şekilde partiler halinde haşlayın. Pierogilerin yüzeye çıkmasından 3 dakika sonra çıkarın.","Tereyağında her iki tarafı altın sarısı olana kadar 2-3 dakika kızartın. Ekşi krema, kavrulmuş soğan ve taze dereotu ile servis edin."',
"czech": '"Bifteği buzdolabından çıkarıp 30 dakika oda sıcaklığında bekletin. Tuz ve karabiber serpin.","Geniş tencerede yağla sebzeleri (havuç, kereviz, soğan) 10 dakika kavurun. Eti ekleyip her tarafı 3 dakika mühürleyin.","250ml su veya et suyu ekleyin. Kapağı kapatıp kısık ateşte 1.5-2 saat, et yumuşayana kadar pişirin. Arada çevirin.","Eti çıkarıp sıcak tutun. Pişme suyundaki sebzeleri blenderdan geçirin. Kremayı ekleyip 5 dakika kaynatın. Tuz ayarı yapın.","Knödel: Unu, yumurtayı, maya ve sütü karıştırıp sosis şekli verin. 15 dakika kaynar suda haşlayıp dilimleyin.","Eti dilimleyip tabağa alın. Kremalı sosu üzerine dökün. Yanına knödel dilimleri ve brusnika (kızılcık) reçeli koyun."',
"hungary": '"Soğanları ince ince kıyın. Geniş tencerede domuz yağı veya zeytinyağını kızdırıp soğanları 15 dakika, camlaşıp hafif kahverengileşene kadar kavurun.","Ateşi kapatın. Kırmızı toz biberi (çok önemli: bol miktarda, 3 yemek kaşığı) ekleyip hızla karıştırın — ateş açıkken eklerseniz yanar ve acılaşır.","Ateşi tekrar açıp kuşbaşı eti ekleyin. 5 dakika mühürleyin. Domatesleri ve kimyonu ekleyin.","Et suyunu ekleyin. Kaynayınca kısık ateşte 1.5 saat pişirin. Patates küplerini ekleyip 30 dakika daha, patates ve et yumuşayana kadar pişirin.","Kıvamı kontrol edin — sulu çorba kıvamında olmalı, çok koyu değil. Gerekirse su ekleyin. Tuz ve biber ayarını yapın.","Kaselere bölüp üzerine bir tutam ekşi krema koyun. Yanında taze ekmek ile sıcak servis edin."',
"romania": '"Lahana turşusunu geniş yapraklar halinde açıp kalın damarları kesin. Çok tuzluysa 30 dakika soğuk suda ıslatın.","Kıymayı yıkanmış pirinç, rendelenmiş soğan, kekik, tuz ve karabiberle yoğurun.","Her lahana yaprağının ortasına 1 yemek kaşığı harç koyun. Alt kenarı katlayın, yanları içe kıvırıp sıkıca sarın.","Geniş fırın tenceresinin dibine doğranmış ekşi lahana ve domates sosunun yarısını yayın. Sarmaları sıkıca yan yana dizin.","Kalan domates sosunu ve 200ml su dökün. Üzerine birkaç dilim tütsülenmiş pastırma koyun.","Kapağı kapatıp 160°C fırında 2.5-3 saat, pirinç tamamen pişene ve sarmaların rengi koyulaşana kadar pişirin. Ekşi krema ve acı biberle servis edin."',
"bulgaria": '"Domatesleri çekirdeklerini çıkarmadan 2cm küp doğrayın. Salatalıkları soyup yarım ay dilimleyin. Biberleri ince şeritler halinde kesin.","Soğanı çok ince yarım ay dilimleyin. Tüm sebzeleri geniş bir kasede nazikçe karıştırın.","3 yemek kaşığı kaliteli sızma zeytinyağı ve 1 yemek kaşığı beyaz şarap sirkesini gezdirin. Hafifçe tuzlayın.","Tabağa düzgün şekilde yayın. Üzerine bol miktarda beyaz salamura peyniri (sirene) iri parçalar halinde ufalayarak serpin.","Tabağın kenarına birkaç siyah zeytin ve sivri yeşil biber yerleştirin.","Soğuk olarak, yanında çıtır beyaz ekmek ve Rakia (geleneksel içki) ile aperatif olarak servis edin."',
"serbia": '"Kıymayı rendelenmiş soğan, ezilmiş sarımsak, tuz ve karabiberle iyice yoğurun — en az 5 dakika. Streç filmle sarıp 2 saat buzdolabında dinlendirin.","Harçtan ceviz büyüklüğünde parçalar koparıp avuçlarınız arasında 8cm uzunluğunda, 2cm kalınlığında parmak şekli verin.","Izgarayı veya döküm tavayı çok yüksek ateşte kızdırın. Çevapiyi yerleştirip 3 dakika hiç dokunmadan, alt taraf mühürlenene kadar pişirin.","Çevirin, 3 dakika daha. Toplam 4 tarafından çevirerek 10-12 dakika pişirin.","Somun ekmeğini ortadan kesip ızgarada 1 dakika ısıtın. İçine kajmak (kaymak peyniri) sürün.","Ekmek arasına 5-6 adet çevapiyi dizin. Üzerine ince doğranmış soğan ve ajvar (kırmızı biber ezmesi) koyarak servis edin."',
}
with open("Models/CountryData.swift") as f:
    content = f.read()
updated = 0
for cid, new_steps in steps.items():
    pattern = rf'(id: "{cid}".*?steps: \[)\s*\n\s*[^\]]*(\])'
    def replacer(m, ns=new_steps):
        return m.group(1) + "\n                " + ns + "\n            " + m.group(2)
    new_content = re.sub(pattern, replacer, content, flags=re.DOTALL, count=1)
    if new_content != content:
        updated += 1
        content = new_content
with open("Models/CountryData.swift", "w") as f:
    f.write(content)
print(f"Batch 4: Updated {updated} countries")
