# -*- coding: utf-8 -*-
#!/usr/bin/env python3
"""Replace short steps with detailed cooking instructions"""
import re

steps = {
"turkey": '"Kıymayı geniş bir kapta soğan, sarımsak, pul biber, kimyon, karabiber, tuz ve salçayla birleştirin. Yapışkan bir kıvam alana kadar en az 10 dakika elinizle kuvvetlice yoğurun.","Yoğrulan harcı streç filmle sarıp buzdolabında en az 2 saat, ideal olarak bir gece boyunca dinlendirin.","Harcı yassı metal şişlerin etrafına 15cm uzunluğunda ve 2cm kalınlığında olacak şekilde sıkıca sarın. Şişi döndüre döndüre bastırarak etin düşmemesini sağlayın.","Mangal kömürlerini yakıp beyaz küle dönmesini bekleyin. Kebapları ızgaraya yerleştirip her tarafı eşit pişecek şekilde 3-4 dakikada bir çevirerek toplamda 12-15 dakika pişirin.","Lavaşı ızgara üzerinde 20 saniye ısıtın. Sumaklı soğanı, ızgara domates ve biberi hazırlayın.","Lavaşı tabağa yayıp kebabı şişten lavaşın üzerine kaydırarak çekin. Yanında sumaklı soğan, ızgara sebzeler ve acılı sos ile servis edin."',
"italy": '"Un, su, maya ve tuzu geniş bir kapta birleştirip pürüzsüz ve elastik olana kadar 10 dakika boyunca yoğurun. Hamur nemli ve hafif yapışkan olmalıdır.","Hamuru nemli bir bezle örtüp oda sıcaklığında (22-24°C) en az 8 saat, ideal olarak 24 saat mayalanmaya bırakın.","Mayalanan hamuru unlü tezgâhta 250g\'lık bezelere ayırın. Her bezeyi alt tarafını katlayarak gergin bir top haline getirin ve üstü kapalı 2 saat daha dinlendirin.","Hamuru sadece parmaklarınızla, ortadan dışa doğru iterek 25-30cm çapında açın. Kenarları biraz kalın bırakarak cornicione (kenar) oluşturun. Oklava kesinlikle kullanmayın.","Ezilmiş San Marzano domateslerini bir tutam tuzla hamur tabanına spiral şekilde kaşıkla yayın. Mozzarellayı elle parçalayarak üzerine dağıtın.","Fırını en yüksek dereceye (250°C+) önceden ısıtın. Pizzayı kürekle fırına sürün ve kenarları kabarana ve tabanda kahverengi lekeler oluşana kadar 5-7 dakika pişirin. Çıkarınca taze fesleğen yapın ve bir iplik zeytinyağı gezdirin."',
"japan": '"Sushi pirincini soğuk suda berraklaşana kadar 4-5 kez yıkayın. Süzüp 30 dakika dinlendirin. Eşit miktarda su ile tencerede kaynatıp 12 dakika kısık ateşte, ardından 10 dakika kapak kapalı dinlendirin.","Pirinç sirkesi, şeker ve tuzu küçük tencerede ılıtıp karıştırarak eritin. Bu karışımı sıcak pirinç üzerine yelpaze ile serinleterek nazikçe karıştırın. Pirinç parlak ve yapışkan olmalıdır.","Sashimi bıçağıyla balığı liflerine 45 derecelik açıyla, tek hamleyle kesin. Her dilim yaklaşık 7cm uzunluğunda, 3cm genişliğinde ve 5mm kalınlığında olmalıdır.","Ellerinizi sirke-su karışımıyla (tezu) ıslatın. 20-25g pirinci avucunuzda hafif sıkarak oval bir yastık şekli verin.","Pirinç yastığın üstüne bıçak ucuyla çok az wasabi sürün. Balık dilimini sol elinize alıp pirinci üzerine yerleştirin ve iki parmağınızla hafifçe bastırarak birleştirin.","Soya sosunu küçük bir tabağa dökün. Nigiriyi balık tarafı aşağıya gelecek şekilde soya sosuna hafifçe değdirip hemen yiyin. Turşu zencefil parçalarını arada damak temizleyici olarak tüketin."',
"france": '"Un, tuz, şeker, maya ve soğuk sütü bir kapta birleştirip kısa süre (5 dk) yoğurun — hamur kaba olabilir. Dikdörtgen şekil verip streç filmle sararak buzdolabında bir gece (12 saat) dinlendirin.","Soğuk tereyağını fırın kâğıdı arasında oklavayla 15x15cm kare bir tabaka haline dövün. Tereyağı katı ama bükülebilir kıvamda olmalıdır.","Hamuru dikdörtgen açıp tereyağını ortasına yerleştirin, hamuru zarf gibi dört kenardan katlayarak tereyağını tamamen sarın.","İlk tur: Hamuru 50cm uzunlukta dikdörtgen açın, üçe katlayın (mektup katlaması). Streç filmle sarıp buzdolabında 1 saat dinlendirin. Bu işlemi toplam 3 kez tekrarlayın.","Son dinlendirmeden sonra hamuru 5mm kalınlığında açın. Tabanı 10cm olan üçgenler kesin. Her üçgeni tabandan uca doğru sıkıca sararak kruvasan şekli verin.","Fırın tepsisine dizin. Oda sıcaklığında (sıcak yerde) hamurlar 1.5-2 katına çıkana kadar 2-3 saat mayalanmaya bırakın. Üzerlerine yumurta sarısı sürüp önceden ısıtılmış 200°C fırında altın sarısı olana ve tabana vurduğunuzda boş ses gelene kadar 15-18 dakika pişirin."',
"mexico": '"Kurutulmuş biberleri saplarını koparıp sıcak suda 20 dakika yumuşayana kadar ıslatın. Suyunu süzün.","Yumuşayan biberleri sarımsak, kimyon, kekik, sirke ve 100ml ananas suyu ile blendere koyup pürüzsüz bir marine sosu oluşturun.","İnce dilimlenmiş etleri derin bir kaba alıp marine sosuyla iyice kaplayın. Üstünü streç filmle kapatıp buzdolabında en az 4 saat, ideal olarak bir gece marine edin.","Marine edilmiş eti buzdolabından çıkarıp 20 dakika oda sıcaklığına gelmesini bekleyin. Döküm tavayı veya ızgarayı çok yüksek ateşte kızdırın. Etleri kenarları karamelize olup hafif kömürleşene kadar her tarafta 2-3 dakika pişirin.","Pişen eti tahtada 3 dakika dinlendirip çok ince ince doğrayın. Ananas dilimlerini de aynı tavada her tarafı 1 dakika olmak üzere kızartın.","Mısır tortillalarını kuru tavada her iki tarafta 15 saniye ısıtın. Tortillaların üzerine doğranmış et, küp ananas, ince doğranmış soğan, kişniş yapın ve üzerine taze misket limonu sıkarak hemen servis edin."',
"india": '"Tavuk parçalarını yoğurt, garam masala, zerdeçal ve kırmızı biber ile geniş bir kasede karıştırın. Streç filmle kapatıp buzdolabında en az 2 saat, ideal olarak 6 saat marine edin.","Marine edilmiş tavukları yüksek ateşteki döküm tavada (veya fırın ızgarasında) her tarafı hafifçe yanıp karamelize olana kadar 3-4 dakika çevirerek mühürleyin. İçi çiğ kalabilir. Kenara ayırın.","Ayrı geniş bir tencerede tereyağını eritin. Soğanı yumuşayıp pembeleşene kadar orta ateşte 8 dakika kavurun. Zencefil-sarımsak ezmesini ekleyip kokusu çıkana kadar 2 dakika daha karıştırın.","Domates püresini ekleyin, kısık ateşte ara sıra karıştırarak 15-20 dakika pişirin. Domates acılığı gidip sos koyulaşmalıdır.","Sosu ateşten alıp el blenderiyle veya blenderda tamamen pürüzsüz olana kadar çekin. Tencereye geri dökün.","Pürüzsüz sosa kremayı ve 2 yemek kaşığı tereyağı daha ekleyin. Mühürlenmiş tavukları sosun içine yerleştirin. Kısık ateşte kapağı hafif aralık bırakarak 15 dakika, tavuklar tamamen pişene ve sos kıvam alana kadar pişirin. Sıcak naan ekmeği veya basmati pirinci ile servis edin."',
"spain": '"Geniş paella tavasında (en az 40cm çapında) zeytinyağını yüksek ateşte kızdırın. Tuzlanmış tavuk parçalarını her tarafı altın sarısı olana kadar 5-6 dakika çevirerek kavurun. Çıkarıp kenara alın.","Aynı tavada taze fasulyeleri 3-4 dakika kavurun. Rendelenmiş domatesi ekleyip suyu çekene kadar 5 dakika daha pişirin.","Tatlı toz biberi ve safranı ekleyin, 30 saniye karıştırıp kokusu çıksın. Tavukları tekrar tavaya koyun.","Kaynar tavuk suyunu tavaya dikkatlice dökün. Kaynayınca pirinci çarpı (X) şekilde eşit olarak tavaya dağıtın. Bu noktadan sonra pirinci kesinlikle karıştırmayın.","İlk 10 dakika yüksek ateşte, ardından 8-10 dakika kısık ateşte, pirinç suyunu çekene ve taneler pişene kadar pişirin. Tavanın altından hafif çıtırtı sesi gelirse socarrat (çıtır taban) oluşuyor demektir — bu iyidir.","Ocağı kapatıp temiz bir havluyla tavanın üstünü örtün. 5 dakika dinlendirin. Limon dilimleri ile doğrudan tavadan servis edin."',
"greece": '"Patlıcanları 1cm kalınlığında yuvarlak dilimleyin. Tuzlayıp süzgeçte 30 dakika bekletin — acı sularını bıraksınlar. Kağıt havluyla kurulayıp zeytinyağında her iki tarafı altın rengini alana kadar kızartın.","Geniş tavada zeytinyağını kızdırın. Soğan ve sarımsağı yumuşayana kadar 5 dakika kavurun. Kıymayı ekleyip suyunu salıp çekene kadar 10 dakika, parçalayarak pişirin.","Kıymaya domatesleri ve tarçını ekleyin. Kısık ateşte 20 dakika, sos koyulaşana kadar pişirin. Tuz ve karabiberle tadını ayarlayın.","Beşamel sosu: 50g tereyağını eritip 50g un ekleyin, 2 dakika kavurun. Sütü yavaş yavaş ekleyip sürekli çırparak koyulaşana kadar (8-10 dk) pişirin. Ateşten alıp 2 dakika soğutun, yumurtaları teker teker çırparak ekleyin.","Yağlanmış fırın kabına sırasıyla: bir kat patlıcan, tüm kıymalı harç, ikinci kat patlıcan ve en üste beşamel sosu dökün. Üzerine Parmesan rendeyin.","Önceden ısıtılmış 180°C fırında üzeri kızarıp kabarcıklanana kadar 40-45 dakika pişirin. Fırından çıkarıp en az 15 dakika dinlendirin — dilimleme bu sayede çok daha kolay olur."',
"usa": '"200g\'lık kıyma toplarını çok gevşek şekilde yuvarlayın — kesinlikle sıkıştırmayın. Sadece bir top şeklinde kalması yeterli.","Döküm tavayı veya griddle\'ı dumanı çıkana kadar (yaklaşık 230°C) çok kızdırın. Kıyma topunu tavaya koyup üzerine spatulayla tüm gücünüzle bastırın — et dümdüz ve çok ince olmalı.","Üzerine sadece bol tuz ve karabiber serpin, başka bir şey eklemeyin. Kenarları kahverengileşip çıtır bir kabuk oluşana kadar tam 90 saniye hiç dokunmadan pişirin.","Spatulayla altından kazıyarak çevirin. Hemen üzerine bir dilim Amerikan peyniri koyun. 60 saniye daha pişirin — peynir erimeye başlamalı.","Bu arada ekmeğin iç yüzlerine ince bir kat tereyağı sürüp ayrı bir tavada altın rengini alana kadar kızartın (yaklaşık 1 dakika).","Alt ekmeğe sos (mayonez+ketçap+hardal karışımı) sürün, marul ve domates koyun. Üzerine peynirli köfteleri yerleştirin, turşu ve soğan ekleyin. Üst ekmeği kapatıp hemen sıcak sıcak servis edin."',
"china": '"Ördeği soğuk su altında iyice yıkayın. Kaynar bir tencere su hazırlayıp ördeğin üzerine kepçeyle 4-5 kez kaynar su dökün — deri gerginleşecek ve gözenekler kapanacaktır.","Bal, soya sosu ve beş baharat karışımını küçük bir kapta iyice karıştırın. Bu karışımı fırçayla ördeğin derisine her yerine eşit şekilde 2-3 kat sürün.","Ördeği bir askıya asarak veya buzdolabında ızgaranın üzerine koyarak deriyi üstü açık şekilde 24 saat tamamen kurutun. Bu adım çıtır derinin sırrıdır — atlamayın.","Fırını 200°C\'ye ısıtın. Ördeği göğsü yukarı bakacak şekilde bir ızgaraya yerleştirin, altına su dolu bir tepsi koyun. İlk 30 dakika 200°C\'de, ardından ısıyı 170°C\'ye düşürüp 60 dakika daha, deri koyu kahverengi ve çıtır olana kadar pişirin.","Fırından çıkarıp 15 dakika dinlendirin. Çok keskin bir bıçakla önce deriyi, sonra et kısımlarını ayrı ayrı, pürüzsüz ince dilimler halinde kesin.","Çin kreplerini buharda veya mikrodalgada 30 saniye ısıtın. Her krebin ortasına bir fırça dolusu hoisin sos sürün, 2-3 dilim ördek eti, birkaç jülyen soğan ve salatalık yerleştirip sıkıca sararak hemen yiyin."',
"thailand": '"Yassı pirinç noodle\'ları büyük bir kaseye koyup oda sıcaklığındaki su ile 30 dakika yumuşayana kadar ıslatın — kaynar su kullanmayın, yoksa hamurlaşırlar. Süzüp kenara alın.","Sos karışımını hazırlayın: Balık sosu, tamarind ezmesi ve palmiye şekerini küçük bir kasede iyice karıştırarak şekeri eritin.","Wok tavayı en yüksek ateşte dumanı çıkana kadar kızdırın. 2 yemek kaşığı yağ ekleyin. Karidesleri atıp pembeleşene kadar 1-2 dakika çevirin. Çıkarıp tabağa alın.","Aynı wok\'a az yağ ekleyip süzülen noodle\'ları ve hazırladığınız sosu atın. Maşayla sürekli karıştırarak noodle\'lar sosu emene kadar 2-3 dakika pişirin.","Noodle\'ları tavanın bir kenarına itin. Boş kalan tarafa yumurtaları kırıp 30 saniye pişmesini bekleyin, sonra parçalayarak noodle\'larla karıştırın.","Taze soğan ve fasulye filizini ekleyip sadece 10-15 saniye soteleyin — filizler diri kalmalı. Karidesleri geri ekleyin. Tabağa alıp üzerine kırılmış kavrulmuş fıstık, misket limonu dilimi ve isteğe göre pul biber serperek servis edin."',
"brazil": '"Siyah fasulyeleri geniş bir kapta bol su ile bir gece (en az 8 saat) ıslatın. Ertesi gün suyunu süzüp taze su ile durulayın.","Geniş ve derin bir tencerede pastırma ve sosis parçalarını orta ateşte kendi yağlarını bırakana kadar 8-10 dakika kavurun. Soğan ve sarımsağı ekleyip yumuşayana kadar 5 dakika daha soteleyin.","Süzülen fasulyeleri ve dana kaburgayı tencereye ekleyin. Üzerini 5cm geçecek kadar su koyun. Defne yapraklarını atın.","Kaynayınca ateşi kısıp kapağı hafif aralık bırakarak en az 2 saat, fasulyeler parmakla kolayca ezilebilecek kadar yumuşayana kadar pişirin. Gerekirse arada su ekleyin.","Pişen fasulyelerden 2 kepçe alıp bir kasede çatalla iyice ezin. Bu püreyi tencereye geri katarak kıvam vermesini sağlayın. Tuzunu kontrol edip ayarlayın.","Geniş bir tabağa beyaz pirinç pilavı, yanına feijoada, üstüne portakal dilimleri ve varsa sote kara lahana (couve) koyarak servis edin."',
"morocco": '"Kuzu parçalarını geniş bir kasede zerdeçal, kimyon, zencefil, tuz ve zeytinyağı ile iyice ovun. Üstünü kapatıp en az 1 saat oda sıcaklığında veya buzdolabında 4 saat marine edin.","Tajin kabında veya kalın tabanlı döküm tencerede zeytinyağını kızdırın. Marine edilmiş kuzu parçalarının dış yüzeylerini yüksek ateşte her tarafı kahverengileşene kadar 2-3 dakika mühürleyin.","Doğranmış soğan ve sarımsağı ekleyin, soğanlar camlaşana kadar 5 dakika kavurun.","Etlerin sadece yarısını kaplayacak kadar sıcak su ekleyin. Kaynayınca ateşi en kısığa getirip kapağı kapatın. Etler çatalla kolayca ayrılacak kadar yumuşayana dek 1.5-2 saat pişirin.","İnce dilimlenmiş limon turşusu kabuklarını ve çekirdeksiz yeşil zeytinleri ekleyin. Kapağı kapatıp 15-20 dakika daha kısık ateşte tıngırdatın.","Bol taze kişniş yaprakları serperek sıcak sıcak, yanında çıtır ekmek veya kuskus ile servis edin."',
"argentina": '"Mangal ateşini çalı veya sert odun kütükleriyle en az 1 saat öncesinden yakın. Kütükler tamamen yanıp beyaz küle dönüşene kadar bekleyin — alev kesinlikle olmamalı.","Bütün etlere sadece bol miktarda iri deniz tuzu serpin. Başka marine veya baharat kullanmayın — Arjantin asado\'nun felsefesi budur.","Önce hızlı pişecek olan sorisları (chorizo) ızgaranın kenarına yerleştirin. Her tarafını 5-6 dakika pişirip misafirler için aperatif olarak servis edin.","Dana kaburgaları kemik tarafı aşağı bakacak şekilde ızgaranın orta-kenar kısmına koyun. Çok düşük dolaylı kömür ısısında 2-2.5 saat boyunca ağır ağır pişirin.","Son 30 dakikada biftek parçalarını ızgaranın en sıcak bölgesine koyun. Her tarafı 3-4 dakika olacak şekilde mühürleyin — içi pembemsi kalmalı (medium-rare).","Tüm pişen etleri tahta kesme tahtasına alıp 5 dakika dinlendirin. Dilimleyip tabağa dizin. Yanına taze hazırlanmış chimichurri sosu (maydanoz, sarımsak, zeytinyağı, sirke) koyarak servis edin."',
"south_korea": '"Her sebzeyi (ıspanak, soya filizi, havuç, kabak, mantarı) ayrı ayrı küçük tavalarda 1 çay kaşığı susam yağı ve bir tutam tuzla 2-3 dakika soteleyin. Sebzeler diri ve canlı renklerini korumalıdır.","İnce dilim sığır etini soya sosu, ezilmiş sarımsak, şeker ve susam yağından oluşan marinasyonda 10 dakika bekletin. Kızgın tavada 2-3 dakika pişirin.","Ayrı bir tavada az yağ ile yumurtayı sarısı patlamadan, kenarları çıtır olacak şekilde sahanda kızartın.","Sıcak bir taş kaseyi (dolsot) veya normal derin kaseyi kızdırıp tabanına 1 çay kaşığı susam yağı gezdirin. Sıcak pilav bastırarak koyun.","Pişirilen sebzeleri ve eti renk uyumuna göre (koyu-açık dönüşümlü) pilavın etrafına yanyana sırayla dizin. Sahanda yumurtayı en tepeye yerleştirin.","Ortaya 1-2 yemek kaşığı gochujang koyun, susam serpin. Yemeden hemen önce tüm malzemeleri kaşıkla iyice karıştırın — taş kasede ise taban pirinçleri çıtırlaşmış olacaktır."',
"peru": '"Çok taze beyaz balığı (levrek veya dil balığı) 2cm\'lik küpler halinde kesin. Geniş cam bir kaseye alıp 1 çay kaşığı tuz serpin.","Leche de tigre hazırlayın: Limon suyunun yarısını sarımsak, acı biberin yarısı, birkaç kereviz yaprağı ve küçük balık kırpıntılarıyla blenderdan geçirin. Bu asitli marin suyunu süzerek balıkların üzerine dökün.","Balığı marinasyonda en fazla 3-5 dakika bekletin — gerçek Peru ceviche\'si sipariş geldiğinde yapılır ve hemen servis edilir. Uzun bekletmek balığı \'pişirir\' ve sertleştirir.","İnce jülyen kesilmiş mor soğanı ve kalan acı biberi balığın üzerine ekleyin. Taze kıyılmış kişnişi serpin.","Tuzunu ve acısını kendi damak tadınıza göre ayarlayın. Son bir miktar taze limon suyu sıkın.","Derin bir tabağa alıp yanına haşlanmış tatlı patates dilimleri, haşlanmış büyük mısır taneleri ve taze marul yaprakları eşliğinde bekletmeden hemen servis edin."',
"germany": '"Izgarayı veya döküm tavayı orta ateşe getirin. Bratwurstların çatlamaması için uçlarına çatalla birkaç hafif delik açın.","Sosisleri ızgaraya veya tavaya yerleştirin. Sık sık çevirerek dışı eşit şekilde çıtır kızarana ve içi tamamen pişene kadar 15-20 dakika boyunca pişirin.","Bu arada soğan halkalarını ayrı bir tavada 1 yemek kaşığı tereyağıyla en kısık ateşte, sürekli karıştırarak 20-25 dakika boyunca koyu kahverengi karamel rengini alana kadar kavurun.","Karamelize soğanlar hazır olunca yarım bardak birayı tavaya dökün. Bira buharlaşıp soğanlar yapışkan bir kıvam alana kadar 3-4 dakika daha pişirin.","Sandviç ekmeklerini ortadan kesin ve iç yüzlerini ızgarada veya tost makinesinde 1 dakika kızartın.","Çıtır ekmeğin içine sosisi yerleştirin, üzerine biralı karamelize soğanları ve Sauerkraut (lahana turşusu) ekleyin. Taneli Alman hardalını bolca sıkarak sıcak sıcak servis edin."',
"portugal": '"Tuzlu morina balığını en az 24-48 saat öncesinden geniş bir kaba koyup soğuk suya yatırın. Her 8 saatte bir suyu değiştirerek fazla tuzu tamamen giderin.","Tuzdan arınan balığı kaynayan suya atıp 10 dakika haşlayın. Çıkarıp soğumaya bırakın, sonra derisini ve kılçıklarını tamamen ayıklayıp eti parmaklarınızla ince ince didikleyin.","Patatesleri kibrit çöpü kalınlığında (3mm) ince şeritler halinde kesin. 170°C yağda altın rengi olana dek 3-4 dakika kızartın. Kağıt havluda süzün.","Geniş bir tavada zeytinyağını kızdırın. İnce jülyen soğan ve sarımsağı camlaşana kadar orta ateşte 8-10 dakika kavurun.","Didiklenmiş balık etini ekleyin, 2-3 dakika soğanlarla harmanlayın. Kızarmış kibrit patatesleri de tavaya ilave edip nazikçe karıştırın.","Yumurtaları bir kasede çırpın. Tavayı ateşten alıp (yumurtalar pişmesin diye) çırpılmış yumurtaları dökün. Tencereyi hafif ateşe geri koyup yumurtalar kremsi bir kıvam alana kadar yavaşça karıştırın. Siyah zeytin ve kıyılmış maydanoz serperek hemen servis edin."',
"vietnam": '"Zencefil kökünü ve soğanı doğrudan ocak ateşinde veya ızgarada, dışları simsiyah yanana kadar közleyin (5-7 dakika). Yanmış dış kabuğu soyup temizleyin — bu işlem dumanlı bir derinlik katar.","Kemikleri kaynar suya atıp 5 dakika haşlayın, suyunu dökün. Bu \'blanching\' adımı kemiklerin pis köpüğünü ve kan artıklarını temizler.","Temiz kemikleri büyük bir tencereye alın. Közlenmiş soğan/zencefil, yıldız anason, tarçın çubuğu ve karanfilleri ekleyin. Üzerini bolca su ile kapatıp kaynattıktan sonra en kısık ateşte en az 6-8 saat, ideal olarak 12 saat kaynatın. Ara sıra yüzeydeki yağ ve köpüğü kepçeyle alın.","Son 2 saatinde sığır döş etini bütün olarak tencereye ekleyin. Et çatalla kolayca ayrılacak kadar pişince çıkarıp ince dilimleyin.","Pirinç noodle\'larını kaynar suda 30 saniye haşlayıp hemen soğuk suya alın. Kaselere bölüştürün.","Noodle\'ların üzerine haşlanmış döş dilimleri ve isterseniz çiğ bonfile dilimleri dizin. Kaynar haldeki et suyunu süzgeçten geçirip doğrudan kaselerin üzerine dökün — sıcak su çiğ eti anında pişirecektir. Yanında taze fesleğen, soya filizi, ince biberler ve misket limonu ile servis edin."',
"lebanon": '"Nohutları büyük bir kapta bol soğuk su ve 1 çay kaşığı karbonatla bir gece (12 saat) ıslatın. Ertesi gün suyu dökün, taze su ile parmaklar arasında kolayca ezilebilecek kadar yumuşak olana dek 1.5-2 saat haşlayın.","Meşakkatli ama çok kritik adım: Haşlanan sıcak nohutları avuçlarınızın arasında ovuşturarak kabuklarını tek tek soyun. Bu işlem humusun ipeksi pürüzsüz yapısının sırrıdır.","Sıcak nohutları (birkaçını süs için ayırın) mutfak robotuna alın. Kendi haşlama suyundan 3-4 yemek kaşığı ekleyerek 2-3 dakika çekin.","Robotun içine tahini, taze sıkılmış limon suyunu, ezilmiş sarımsağı, tuzu ve kimyonu ekleyin. Robot çalışırken kapaktan 3-4 buz küpü atın — bu humusu havalandırıp kreması gibi bembeyaz yapacaktır.","5 dakika kesintisiz çekin. Tadına bakıp tahin/limon oranını damağınıza göre ince ayar yapın. Kıvam yoğurt gibi akıcı ve ipeksi olmalıdır.","Geniş düz bir tabağa kaşıkla yayın, kaşığın tersiyle ortasına dairesel bir çukur açın. Çukura bol sızma zeytinyağı gezdirin, kenara ayırdığınız nohutları, kırmızı toz biber ve birkaç maydanoz yaprağı koyup sıcak pide ile servis edin."',
"united_kingdom": '"Patatesleri kalın kalın (1.5cm genişliğinde chip şeklinde) kesin ve nişastasını salması için soğuk suda 30 dakika bekletin. Süzüp kağıt havluyla tamamen kurulayın.","İlk kızartma: 140°C yağda patatesleri 6-8 dakika haşlar gibi yumuşak olana dek pişirin — renk almamalılar. Çıkarıp tepsiye dizin. İkinci kızartma: Yağı 190°C\'ye çıkarıp patatesleri 2-3 dakika altın sarısı ve çıtır olana dek tekrar kızartın.","Kaplama hamurunu hazırlayın: Unu bir kaseye eleyip ortasına çukur açın. Soğuk birayı yavaş yavaş ekleyerek çırpın — hamur koyu krema kıvamında, topaksız ve pürüzsüz olmalıdır.","Balık filetolarını kağıt havluyla iyice kurulayın — nemli balık hamuru tutmaz. Önce hafifçe unlayın, sonra kuyruğundan tutup tamamen sıvı hamura batırın.","Hamurlanan balığı dikkatlice 180°C kızgın yağa bırakın. Her iki tarafı altın sarısı ve çıtır olana kadar 5-6 dakika kızartın. Kağıt havluda süzün.","Tabağa çıtır patatesleri ve balığı koyun. Üzerine tuz ve malt sirkesi serpin. İsteğe bağlı olarak ezilmiş bezelye veya tartar sos ile servis edin."',
"egypt": '"Mercimekleri diri kalacak şekilde (lapa olmadan) kaynayan tuzlu suda 20-25 dakika haşlayın. Süzüp kenara alın.","Ayrı bir tencerede pirinci 1 yemek kaşığı tereyağında hafifçe kavurup 1.5 kat su ile kısık ateşte suyunu çekene kadar pişirin.","Makarnaları paket üzerindeki sürede haşlayın. Nohutları da önceden haşlayıp hazır bulundurun.","Domates sosunu yapın: 4 diş sarımsağı zeytinyağında 1 dakika kavurun, domates püresini ekleyin. 3 yemek kaşığı sirke ve pul biberi ekleyip 15 dakika koyulaşana dek pişirin.","İnce dilimlenmiş soğanları bol yağda sürekli karıştırarak koyu kahverengi olana dek 15-20 dakika kızartın. Çıtır ve karamelize olmalılar.","Derin kaselere sırasıyla pirinç, üstüne makarna, mercimek ve nohut koyun. Bolca domates sosunu tepeye gezdirin, çıtır soğanları en üste serpin. İsteğe göre ekstra acı sos ekleyin."',
"canada": '"Patatesleri 1.5cm kalınlığında eşit çubuklar halinde kesin. Soğuk suda 30 dakika ıslatıp nişastasını alın, tamamen kurulayın.","Birinci kızartma: 150°C yağda 6-7 dakika, patateslerin içi yumuşayana ama renk almayacak şekilde pişirin. Çıkarıp 10 dakika dinlendirin.","İkinci kızartma: Yağı 190°C\'ye yükseltip patatesleri tekrar atın. Dışı altın sarısı ve çıtır olana kadar 2-3 dakika kızartın. Bol tuz serpin.","Bu arada et sosu (gravy) kasesini ocağa koyup hafifçe tıngırdayacak şekilde ısıtın — kaynar halde olmalı.","Geniş bir kaseye sımsıcak patatesleri alın. Hemen üzerine oda sıcaklığındaki taze peynir parçalarını (curd) bolca dağıtın.","Kaynar haldeki gravy sosunu doğrudan patateslerin ve peynirin üzerine dökün. Peynirler sıcakla hafifçe esneyip bükülmeye başlamalı ama tam erimemelidir. Hemen tüketin — poutine soğuyunca büyüsünü kaybeder."',
}

# For countries not in the detailed dict, we'll leave them as-is
with open("Models/CountryData.swift") as f:
    content = f.read()

import re
updated = 0
for cid, new_steps in steps.items():
    pattern = rf'(id: "{cid}".*?steps: \[)\s*\n\s*[^\]]*(\])'
    def replacer(m):
        return m.group(1) + "\n                " + new_steps + "\n            " + m.group(2)
    new_content = re.sub(pattern, replacer, content, flags=re.DOTALL, count=1)
    if new_content != content:
        updated += 1
        content = new_content

with open("Models/CountryData.swift", "w") as f:
    f.write(content)

print(f"Updated steps for {updated} countries")
