# -*- coding: utf-8 -*-
import re
steps = {
"tunisia": '"Kuzu etini küçük parçalar halinde tencerede zeytinyağıyla her tarafı 5 dakika mühürleyin. Soğan ve sarımsak ekleyip 3 dakika kavurun.","Domates püresi, harissa, tuz ve baharatları ekleyin. Et suyunu dökün, kaynayınca kısık ateşte 45 dakika pişirin.","Kabak ve havucu ekleyip 15 dakika daha, sebzeler yumuşayana kadar pişirin. Haşlanmış nohutları son 5 dakikada ekleyin.","Kuskusu geniş bir kaba koyun. Üzerine kaynar su dökün (1:1 oranında). 5 dakika üstünü kapatıp bekletin.","Çatalla kuskusu kabartın, 1 yemek kaşığı zeytinyağı ve tereyağı karıştırın. Tuzlayın.","Tabağa kuskusu yığın, et ve sebzeleri üstüne dizin. Bol sos gezdirip harissa ile servis edin."',
"algeria": '"Kuzu etini tencerede yağla 5 dakika mühürleyin. Soğan ve sarımsak ekleyip 3 dakika kavurun.","Domates püresi, nohut, baharatlar ve 500ml su ekleyin. Kısık ateşte 1 saat, et yumuşayana kadar pişirin.","Yufka ekmeklerini elle küçük parçalara bölün. Buhar tenceresine veya kevgire koyup 10 dakika buharda ısıtın.","Parçalanan ekmekleri geniş tabağa yayın. Tereyağı eritip üzerine gezdirin.","Et yahnisinin suyundan bolca ekmeklerin üzerine dökün. 2 dakika emmesini bekleyin.","Et parçalarını ve nohutları üstüne dizin. Kalan sosu gezdirip sıcak servis edin."',
"ghana": '"Manyoku soyup büyük parçalar halinde kesin. Olgun yeşil muzu soyun. İkisini de kaynar suda 20-25 dakika yumuşayana kadar haşlayın.","Haşlanan manyok ve muzu büyük havanda veya mutfak robotunda yapışkan ve elastik bir hamur kıvamına gelene kadar dövün.","Et çorbası: Keçi etini soğan, domates, biber ve palmiye yağı ile 1.5 saat, et yumuşayana dek pişirin.","Scotch bonnet biberi bütün olarak son 15 dakikada çorbaya ekleyin — çok acı istenmiyorsa patlatmayın.","Fufu\'dan yumruk büyüklüğünde toplar yapıp tabağa koyun.","Yanına et çorbasını koyun. Fufu\'dan parçalar koparıp çorbaya daldırarak, çiğnemeden yutarak yiyin — bu geleneksel yeme şeklidir."',
"senegal": '"Balığı temizleyip deri üzerinde çizikler atın. Maydanoz, sarımsak, acı biber ve limon karışımını çiziklere doldurun. 30 dakika marine edin.","Geniş tencerede yağı kızdırıp balığı her iki tarafı 3 dakika olacak şekilde kızartın. Çıkarın.","Aynı yağda soğanları 5 dakika kavurun. Domates salçası, tamarind ve su ekleyip 15 dakika kaynatın.","Patlıcan, lahana ve havuçları ekleyin. 15 dakika daha, sebzeler yumuşayana kadar pişirin.","Pirinci yıkayıp tencereye ekleyin. Su seviyesini ayarlayıp kapağı kapatın. Kısık ateşte 20-25 dakika, pirinç pişene kadar.","Balığı son 5 dakikada üste yerleştirin. Büyük tabağa pirinç, sebzeler ve balığı düzelterek servis edin."',
"kenya": '"Keçi etini büyük parçalar halinde bırakın. Sadece bol iri tuz ve limon suyu ile ovun — başka baharat kullanmayın.","Odun kömürü ateşi yakın, korlar beyaz küle dönene kadar bekleyin. Izgarayı temizleyip yağlayın.","Eti ızgaraya koyup çok düşük ateşte, her tarafını 15-20 dakikada bir çevirerek toplam 1-1.5 saat yavaş yavaş pişirin.","Kachumbari salatası: Domates, soğan ve kişnişi ince doğrayın. Limon suyu ve tuz ile karıştırın.","Ugali: 500ml suyu kaynatın. Mısır ununu yavaş yavaş ekleyip tahta kaşıkla sürekli karıştırarak 10 dakika, sert hamur kıvamına gelene kadar pişirin.","Eti tahtada parçalayıp tabağa alın. Yanında ugali ve kachumbari ile servis edin."',
"tanzania": '"1 litre suyu geniş tencerede kaynattın. Ateşi kısın.","Mısır ununu bir avuç bir avuç, sürekli karıştırarak ekleyin — topak oluşmamalı.","Karıştırma işlemini tahta kaşıkla 10-15 dakika, hamur çok sert ve tencereden ayrılana kadar sürdürün.","Et yahnisi: Dana etini soğan, domates ve biberle 45 dakika kısık ateşte pişirin. Tuzlayın.","Ugali\'yi ıslak ellerle büyük bir top haline getirip tabağa ters çevirerek koyun.","Yanına et yahnisini koyun. Ugali\'den parçalar koparıp çukur yaparak yahniyi scooplayarak yiyin."',
"morocco2": '"Dana etini kuşbaşı doğrayıp tencerede yağla 5 dakika mühürleyin.","Soğan, sarımsak ve zencefili ekleyip 3 dakika kavurun. Domatesleri ekleyip 5 dakika pişirin.","250ml su ekleyip kısık ateşte 40 dakika, et yumuşayana kadar pişirin.","Yıkanmış ıspanakları avuç avuç tencereye ekleyin — ıspanak çok çabuk iner.","5 dakika daha pişirip tuz ve biber ile tadını ayarlayın.","Sıcak beyaz pirinç pilavıyla birlikte derin tabakta servis edin."',
"new_zealand": '"Toprak çukuru kazın (60cm derinliğinde). İri nehir taşlarını odun ateşi üzerinde 3-4 saat ısıtın.","Çukurun dibine sıcak taşları yerleştirin. Üzerine ıslak çuval bezi serin.","Et parçalarını (kuzu, tavuk) ve sebzeleri (patates, tatlı patates, kabak, lahana) tel sepetlere veya folyo paketlere koyup taşların üzerine yerleştirin.","Üzerine tekrar ıslak çuval bezleri örtün, toprakla kapatın. Hava almamali.","3-4 saat toprak altında buharla yavaş yavaş pişmesini bekleyin.","Dikkatli kazıp çıkarın. Et kemikten ayrılacak kadar yumuşak, sebzeler dumanlı bir tatlılıkta olacaktır. Hep birlikte paylaşarak yiyin."',
"fiji": '"Çok taze beyaz balığı 2cm küpler halinde kesin. Cam kaseye alıp üzerine limon suyunu sıkın.","Buzdolabında 15-20 dakika marine edin — balık dıştan beyazlaşmalı ama ortası yarı saydam kalmalı.","Hindistancevizi sütünü ekleyip nazikçe karıştırın.","Küp doğranmış domates, ince dilimlenmiş soğan ve kırmızı biberi ekleyin.","Tuzla tadını ayarlayın. Buzdolabında 10 dakika daha dinlendirin — tüm tatlar kaynaşsın.","Hindistancevizi kabuğu veya cam kaselerde soğuk olarak servis edin."',
"jamaica2": '"Domuz etini kuşbaşı doğrayın. Portakal suyu, limon suyu, sarımsak ve soğanla marine edip buzdolabında 4 saat bekletin.","Marine suyunu süzüp eti tencereye alın. Üzerini geçecek kadar su koyup 45 dakika, et yumuşayana kadar haşlayın. Süzün.","Geniş derin tavada 500ml yağı 175°C\'ye kızdırın. Haşlanmış et parçalarını 8-10 dakika, dışı çıtır ve koyu altın rengi olana kadar kızartın.","Kızarırken pikliz hazırlayın: İnce dilim lahana, havuç, scotch bonnet biber ve soğanı sirke ile karıştırın.","Kızarmış etleri kağıt havluda süzün.","Tabağa pirinç pilavı, üstüne çıtır griot parçaları ve yanına pikliz koyarak servis edin."',
"denmark": '"Çavdar ekmeğini 1cm kalınlığında düzgün dilimleyin. Her dilimin bir yüzüne ince kat tereyağı sürün.","Ringa balığı versiyonu: Marine ringa filetolarını ekmek üzerine düzgün dizin. Üzerine ince soğan halkaları, kapari ve dereotu koyun.","Karides versiyonu: Küçük karidesleri ekmek üzerine yığın. Mayonez, limon suyu ve dereotundan sos hazırlayıp üzerine gezdirin.","Yumurtalı versiyon: Haşlanmış yumurtaları dilimleyip ekmek üzerine dizin. Mayonez, tuz, biber ve taze dereotu ekleyin.","Her smørrebrød\'ü ayrı tabağa koyup kenarını taze salata yaprakları ile süsleyin.","Soğuk servis edin — bıçak ve çatalla, altta başlayarak yenir, elle tutulmaz."',
"norway": '"Çok taze alabalık filetosunu derin bir kaba koyun. Bol iri tuz serperek tamamen kaplayın.","Buzdolabında 3-5 gün (geleneksel yöntemde 2-3 ay) bekletin. Her gün biriken suyu dökün.","Fermente süre dolunca balığı tuzdan çıkarıp soğuk suyla durulayın. Kağıt havluyla kurulayın.","Çok keskin bıçakla kağıt inceliğinde dilimler kesin.","Lefse (patates ekmeği) yapın veya hazır kullanın: Haşlanmış patatesi ezin, un ve tereyağıyla hamur yapıp tavada pişirin.","Lefse üzerine ekşi krema sürün, rakfisk dilimlerini yerleştirip ince doğranmış kırmızı soğan ve dereotu serpin. Sararak yiyin."',
"finland": '"Çavdar unu, su ve tuzu yoğurup sert ve elastik bir hamur yapın. 30 dakika dinlendirin.","Hamuru ikiye bölüp her birini 25cm çapında oval açın — 1cm kalınlığında olmalı.","Ortaya temizlenmiş muikku balıklarını ve domuz pastırma dilimlerini katlar halinde dizin. Tuzlayın.","Hamur kenarlarını ortaya doğru katlayıp sıkıca kapatın — kayık veya ekmek şekli almalı.","150°C fırında 4-5 saat, çok yavaş pişirin. Her saat başı üstüne tereyağlı su fırçalayın.","Kabuk sertleşip koyu kahverengi olacak. Dilimleyince iç kısmı nemli ve lezzetli olmalı. Tereyağıyle sıcak yiyin."',
"singapore": '"Pirinç noodle\'ları kaynar suda 2 dakika haşlayıp soğuk suya alın, süzün.","Laksa macununu tencerede 3 yemek kaşığı yağla 5 dakika, yağ ayrışana kadar kavurun.","Hindistancevizi sütünü ve 400ml su ekleyin. Kaynayınca 10 dakika kısık ateşte pişirin. Balık sosu ve şekerle tatlandırın.","Tofu\'yu küp doğrayıp tavada çıtır olana kadar 3-4 dakika kızartın. Karidesleri 2 dakika soteleyin.","Kaselere noodle\'ları paylaştırın. Kaynar laksa suyunu üzerlerine dökün.","Üzerine karides, tofu, haşlanmış yumurta yarımları, fasulye filizi ve taze kişniş dizin. Acı yağ ve limon ile servis edin."',
"taiwan": '"Dana etini büyük parçalar halinde tencerede yağla her tarafı 3 dakika mühürleyin.","Soğan, sarımsak ve zencefili ekleyip 2 dakika kavurun. Domatesleri, soya sosunu ekleyin.","Yıldız anason, kuru biber ve 1L su ekleyin. Kaynayınca kısık ateşte 2-3 saat, et çatalla kolayca ayrılana kadar pişirin.","Eti çıkarıp kalın dilimleyin. Sosu süzerek temiz tencereye alın — berrak ve yoğun olmalı.","Taze buğday noodle\'larını kaynar suda 3 dakika haşlayın. Bok choy\'u son 30 saniyede ekleyin. Süzün.","Derin kaselere noodle ve bok choy koyun. Üstüne et dilimlerini dizin. Kaynar sosu dökün ve taze yeşil soğan serperek servis edin."',
"hong_kong": '"Har Gow hamuru: Buğday nişastası ve tapioka ununa kaynar su ekleyerek yoğurun — yarı saydam elastik bir hamur olmalı.","Karides içi: Temiz karidesleri kabaca kıyın. Susam yağı, soya sosu, tuz ve beyaz biberle karıştırın.","Hamuru küçük toplar yapıp yağlı bıçakla 8cm daire düzleştirin. Ortaya karides harcı koyup kenarlarını 7-8 kıvrım yaparak kapatın.","Siu Mai: Wonton hamurunu açın, domuz kıyma-karides harcını ortaya koyup hamuru yukarı toplayarak üstü açık şekilde şekillendirin.","Bambu sepetlerin tabanına napa lahana yaprakları serin. Dim sum\'ları aralıklı dizin. Kaynayan su üzerinde 8-10 dakika buharda pişirin.","Soya sosu, Çin sirkesi ve ince kıyılmış zencefil karışımından dip sos hazırlayıp sıcak servis edin."',
"cambodia": '"Kroeung macunu: Limon otu, galangal, zerdeçal, sarımsak ve şalotu havanda veya blenderde macun haline getirin.","Balık filetosunu küçük parçalara bölün. Kroeung macunu, hindistancevizi sütü ve balık sosuyla marine edin.","Yumurtayı çırpıp karışıma ekleyin — bu pişerken puding kıvamı verecektir.","Muz yapraklarını 30 saniye alevden geçirip yumuşatın. Kase şekli vererek karışımı içine dökün.","Buharlı tencerede 20-25 dakika, karışım pıhtılaşıp puding kıvamına gelene kadar pişirin.","Üzerine kalın hindistancevizi kreması, ince kıyılmış kırmızı biber ve kaffir lime yaprağı koyarak servis edin."',
"laos": '"Tavuk kıymayı yağsız tavada, sürekli parçalayarak 5-6 dakika pişirin. Suyunu tamamen çekmeli.","Ateşten alıp geniş kaseye aktarın. Taze limon suyu ve balık sosunu hemen ekleyip karıştırın.","Kavrulmuş pirinç tozu yapın: Yapışkan pirinci kuru tavada 5 dakika, altın rengine gelene kadar kavurun. Havanda toz edin.","Pirinç tozunu, ince dilimlenmiş acı biberi, kıyılmış nane ve kişnişi ete ekleyin. İyice karıştırın.","Tadına bakıp limon-balık sosu dengesini ayarlayın — ekşi, tuzlu ve hafif tatlı olmalı.","Göbek marul yapraklarını kase gibi açıp içine larb koyun. Marul yapraklarıyla sararak yiyin."',
"portugal2": '"Krema: Sütü vanilya çubuğu ve limon kabuğu rendesiyle tencerede kaynatın. Un ve şekeri ayrı kapta karıştırıp yumurta sarılarını ekleyin. Sıcak sütü yavaş yavaş yumurtalara ekleyin.","Karışımı ateşe geri koyup sürekli karıştırarak 5-7 dakika, koyulaşana kadar pişirin. Süzgeçten geçirip soğutun.","Milföy hamurunu 2mm kalınlığında açıp sıkı rulo sarın. 1cm kalınlığında dilimlere kesin.","Her dilimi küçük tart kalıbının içine parmağınızla bastırarak kalıbı kaplayın — kenarlar hamurdan 5mm yukarı çıkmalı.","Soğumuş kremayı kalıpların 3/4\'üne kadar doldurun.","250°C (çok yüksek) fırında 12-15 dakika, üst kısımda kahverengi yanık lekeleri oluşana kadar pişirin. Soğutup tarçın ve pudra şekeri serperek servis edin."',
"scotland": '"İç organları (ciğer, yürek, akciğer) 2 saat kaynar suda haşlayın. Çıkarıp soğutun, ince kıyın veya robottan geçirin.","Yulaf ezmesini kuru tavada 5 dakika, hafif renk alana kadar kavurun — fındıksı aroma kazanır.","Kıyılmış iç organları yulaf ezmesi, ince kıyılmış soğan, iç yağı (süet), tuz, karabiber ve yenibaharla iyice karıştırın.","İşkembeyi temizleyip karışımı içine doldurun. İplikle sıkıca bağlayın — şişmeye yer bırakın, çok sıkı doldurmayın.","Büyük tencereye koyup su ile örtün. Kısık ateşte 2.5-3 saat haşlayın.","Dilimleyip yanında \'neeps and tatties\' (şalgam ve patates püresi) ve bir kadeh viski ile servis edin."',
"wales": '"Kuzu boyun etini geniş tencerede 2 yemek kaşığı yağla her tarafı 5 dakika mühürleyin.","Doğranmış soğanları ekleyip 5 dakika kavurun. Kuzu eti suyunu veya su ekleyin, kaynattın.","Havuç, pırasa ve şalgamı ekleyin. Kısık ateşte 1.5 saat, et kemikten ayrılacak kadar pişirin.","Patates dilimlerini üste dizin, kapağı kapatıp 30 dakika daha pişirin.","Taze kıyılmış maydanoz serpin. Tuz ve biber ile tadını ayarlayın.","Derin kaselere bölüp yanında peynirli ekmek (Caerphilly peyniri ile) servis edin."',
"trinidad": '"Bara hamuru: Un, maya, zerdeçal, kimyon ve tuzu ılık suyla yoğurup 1 saat mayalanmaya bırakın.","Nohut körisi: Nohutları haşlayın. Soğan ve sarımsağı kavurun. Köri tozu ve kimyon ekleyip 2 dakika kavurun. Nohut ve su ekleyip 20 dakika pişirin.","Mayalanan hamurdan yumruk büyüklüğünde toplar alıp yassılaştırın (10cm çap, 5mm kalınlık).","Barları 170°C yağda her iki tarafı 2-3 dakika, şişip altın sarısı olana kadar kızartın.","Bir bara avuca alıp ortasına kepçeyle nohut körisi koyun. İkinci barayı üste kapatın.","Üzerine acı sos (tamarind ve scotch bonnet biber sosu) gezdirerek hemen servis edin."',
"Cuba2": '"Tavuğu parçalayıp tuzlu suda 25-30 dakika haşlayın. Çıkarıp kemiklerinden ayırın.","Kabak tohumları ve susamı ayrı ayrı kuru tavada 3-4 dakika, renk alıp kokması çıkana kadar kavurun.","2 adet tortillayı da kuru tavada her iki tarafı 1 dakika kızartın. Hepsini domates ve biberle blenderda pürüzsüz sos haline getirin.","Geniş tencerede yağ kızdırıp sosu 10 dakika, koyulaşana kadar kavurun.","Tavuk parçalarını sosa ekleyip 15 dakika kısık ateşte pişirin. Tuz ayarını yapın.","Beyaz pirinç pilavı ve sıcak mısır tortillası ile servis edin."',
"honduras": '"Un tortillalarını kuru tavada her iki tarafı 30 saniye ısıtın — esnek ama çıtır noktalar oluşmalı.","Kızarmış fasulye ezmesi: Haşlanmış fasulyeleri tavada yağla ezerek 10 dakika, koyulaşana kadar kavurun. Tuzlayın.","Tortillanın bir yarısına sıcak fasulye ezmesini kaşıkla yayın.","Üzerine bol ufalanmış taze peynir ve ekşi krema ekleyin.","Avokado dilimlerini üste dizin. İsteğe göre sahanda yumurta veya et de ekleyebilirsiniz.","Tortillayı ikiye katlayın (kapatmadan). Sıcak sıcak servis edin — kahvaltı, öğle veya akşam her öğünde yenir."',
}
with open("Models/CountryData.swift") as f:
    content = f.read()
updated = 0
for cid, new_steps in steps.items():
    pattern = rf'(id: "{cid}".*?steps: \[)\s*\n\s*[^\]]*(\])'
    def replacer(m, ns=new_steps):
        return m.group(1) + "\n                " + ns + "\n            " + m.group(2)
    new_content = re.sub(pattern, replacer, content, flags=re.DOTALL, count=1)
    if new_content != content:
        updated += 1
        content = new_content
with open("Models/CountryData.swift", "w") as f:
    f.write(content)
print(f"Batch 6: Updated {updated} countries")
