# -*- coding: utf-8 -*-
import re
steps = {
"russia": '"Bütün sebzeleri (pancar, lahana, patates, havuç, soğan) ayrı ayrı ince doğrayın veya rendeleyin. Pancarı en sona saklamak rengi korur.","Geniş bir tencerede 2 yemek kaşığı zeytinyağını kızdırın. Soğanı 5 dakika kavurun, havucu ekleyip 3 dakika daha soteleyin.","Et suyunu ekleyip kaynattıktan sonra patates ve lahana parçalarını atın. Orta ateşte 15 dakika, patatese bıçak rahatça girene kadar pişirin.","Ayrı tavada rendelenmiş pancarı 1 yemek kaşığı sirke ile 10 dakika kavurun — sirke parlak kırmızı rengi korur.","Kavrulmuş pancarı tencereye ekleyin, 5 dakika daha birlikte pişirin. Tuz ve karabiberle tadını ayarlayın.","Kaselere bölüp her birinin üzerine 1 yemek kaşığı ekşi krema ve taze dereotu koyarak sıcak servis edin."',
"australia": '"Geniş tavada 1 yemek kaşığı zeytinyağını kızdırın. Soğanı 5 dakika kavurun, kıymayı ekleyip parçalayarak 8-10 dakika pişirin.","Domates salçası ve et suyunu ekleyin. Kısık ateşte 15 dakika, sos koyulaşana kadar pişirin. Tuz ve karabiberle tatlandırın.","Milföy hamurunu 3mm kalınlığında açın. Yuvarlak kalıplarla alt ve üst kapak olarak kesin.","Yağlanmış turta kalıplarına alt hamuru yerleştirin. Soğumuş et harcını doldurun, kenarları yumurtayla fırçalayın.","Üst kapağı kapatın, kenarları çatalla bastırarak mühürleyin. Üstüne yumurta sarısı sürün ve bıçakla buhar deliği açın.","200°C önceden ısıtılmış fırında 25-30 dakika, üstü altın sarısı olana kadar pişirin. 5 dakika dinlendirip domates sosuyla servis edin."',
"sweden": '"Ekmek kırıntılarını sütte 5 dakika ıslatın. Kıymayı rendelenmiş soğan, ıslatılmış ekmek kırıntısı, yumurta, tuz ve karabiberle iyice yoğurun.","Ellerinizi ıslatarak harçtan ceviz büyüklüğünde (yaklaşık 3cm) toplar yuvarlayın. Tepsiye dizin.","Geniş tavada tereyağını orta-yüksek ateşte eritin. Köfteleri tek sıra halinde yerleştirip her tarafı altın kahverengisi olana kadar 8-10 dakika çevirerek kızartın.","Köfteleri çıkarıp aynı tavaya 2 yemek kaşığı un serpin, 1 dakika kavurun. Kremayı yavaş yavaş ekleyerek koyulaşana kadar 5 dakika pişirin.","Köfteleri sosa geri koyup 5 dakika daha kısık ateşte sos ile birlikte pişirin. Tuz ayarını yapın.","Tabağa köfteleri kremalı sosla birlikte alın. Yanına lingonberry reçeli, haşlanmış patates ve turşu koyarak servis edin."',
"ethiopia": '"Teff ununu ılık suyla karıştırıp sıvı bir hamur yapın. Üstünü örtüp oda sıcaklığında 2-3 gün fermente olmaya bırakın — hamur ekşimeli ve kabarcıklı olmalı.","Yapışmaz tavayı orta ateşte ısıtın. Fermente hamurdan ince bir tabaka halinde spiral şekilde dökün. Kapağı kapatıp 2-3 dakika, üstü gözenekli ve kuruymuş görünene kadar sadece bir tarafını pişirin.","Doro Wot için: 4 büyük soğanı yağsız tencerede 15-20 dakika, koyu kahverengileşene kadar kavurun — bu sabır gerektiren adım lezzeti belirler.","Berbere baharatını ve tereyağını ekleyip 3 dakika karıştırın. Tavuk parçalarını atıp her tarafını 3 dakika çevirerek mühürleyin.","1 su bardağı su ekleyip kapağı kapatın. Kısık ateşte 45 dakika, tavuk kemikten ayrılacak kadar yumuşayana dek pişirin.","Soyulmuş haşlanmış yumurtaları son 10 dakikada ekleyin. Geniş bir tabağa injera yayıp üzerine Doro Wot\'u dökerek parçalayarak yiyin."',
"colombia": '"Kırmızı fasulyeleri bir gece ıslatıp ertesi gün 1 saat haşlayın veya konserve kullanın. Süzün.","Ayrı tencerede pirinci 2 kat su ile tuzlu olarak kısık ateşte 18 dakika, suyunu çekene kadar pişirin.","Geniş tavada kıymayı soğan ve sarımsakla 10 dakika kavurun. Kimyon ve tuz ekleyip karıştırın.","Olgun muzları boyuna ikiye kesip tereyağlı tavada her iki tarafı altın rengine gelene kadar 2-3 dakika kızartın.","Yumurtaları ayrı tavada sahanda kızartın — kenarları çıtır, sarısı akıcı olmalı.","Büyük bir tabağa pilav, fasulye, kıyma, kızarmış muz, sahanda yumurta, arepa ve avokado dilimlerini yan yana düzenleyerek servis edin."',
"nigeria": '"Biberleri ve soğanları kabaca doğrayıp blenderda pürüzsüz bir sos haline getirin. Pirinci yıkayıp 30 dakika ıslatın, süzün.","Geniş tencerede bitkisel yağı kızdırıp kalan soğanı 5 dakika kavurun. Biber-domates püresini ekleyip 15 dakika, su salıp çekene kadar pişirin.","Domates salçasını ekleyip 5 dakika daha kavurun. Kekik, defne ve tuz atın.","Tavuk suyunu ve yıkanmış pirinci ekleyin. Kaynayınca ateşi en kısığa getirin.","Kapağı sıkıca kapatıp (araya folyo koyabilirsiniz) 30 dakika hiç kapak açmadan pişirin.","Kapağı açıp pirinci çatalla kabartın. Kızarmış muz ve ızgara tavuk ile servis edin."',
"south_africa": '"Fırını 180°C\'ye önceden ısıtın. 2 dilim beyaz ekmeği süte batırıp 5 dakika yumuşamaya bırakın.","Geniş tavada soğan ve sarımsağı 5 dakika kavurun. Kıymayı ekleyip parçalayarak 10 dakika pişirin.","Köri tozu, kimyon ve zerdeçali ekleyip 2 dakika kavurun. Kayısı reçeli, limon suyu ve süte batırılıp sıkılmış ekmeği karıştırın.","Et karışımını fırın kabına düzgünce yayın. Defne yapraklarını üstüne yerleştirin.","Yumurtaları sütle çırpıp kıymanın üzerine eşit şekilde dökün — bu kremalı üst tabakayı oluşturacak.","180°C fırında 35-40 dakika, üstü altın sarısı ve pıhtılaşana kadar pişirin. 10 dakika dinlendirip sarı pilavla servis edin."',
"indonesia": '"Pirinci önceki gün pişirip buzdolabında bir gece bekletin — kuru taneli pirinç en iyi sonucu verir.","Wok tavayı yüksek ateşte kızdırın. 2 yemek kaşığı yağ ekleyip sarımsak ve biberi 30 saniye kavurun.","Tavuk ve karidesleri ekleyip 3-4 dakika, tamamen pişene kadar çevirin.","Soğuk pirinci ekleyin. Tatlı soya sosu ve balık sosunu gezdirip maşayla sürekli karıştırarak 3-4 dakika pişirin. Pirinç hafif karamelize olmalı.","Pirinci tavanın bir kenarına itin, boşluğa yumurtaları kırıp 30 saniye bekletin, sonra pirinçle karıştırın.","Tabağa tersine çevrilmiş kase şeklinde pirinç yığın. Yanına sahanda yumurta, krupuk cipsleri ve salatalık dilimleri koyarak servis edin."',
"malaysia": '"Pirinci yıkayıp hindistancevizi sütü, pandan yaprağı, zencefil dilimi ve bir tutam tuzla tencereye koyun. Kaynayınca kısık ateşte 18 dakika pişirin.","Sambal sos: Kurutulmuş biberleri ıslatıp blenderdan geçirin. Yağda soğan, sarımsak ve biber ezmesini 15 dakika, yağ ayrışana kadar kavurun. Şeker ve tuz ekleyin.","Ançüezleri kağıt havluyla kurulayıp az yağda çıtır olana kadar 3 dakika kızartın.","Fıstıkları kuru tavada orta ateşte 5 dakika, hafif renk alana kadar kavurun.","Yumurtaları kaynamış suda 8 dakika haşlayıp soğuk suya alın. Soyup ikiye kesin.","Muz yaprağını veya tabağı açın. Ortaya hindistancevizi sütlü pilavı koyun. Etrafına sambal, ançüez, fıstık, yumurta yarımları ve salatalık dilimleri dizin."',
"philippines": '"Tavuk parçalarını geniş tencereye koyup soya sosu, sirke, ezilmiş sarımsak, defne yaprakları ve karabiberi ekleyin. Karıştırıp 30 dakika oda sıcaklığında marine edin.","Tencereyi kapağı kapalı olarak orta ateşe koyun. Kaynayınca ateşi kısıp 30-35 dakika, tavuk tamamen pişene kadar pişirin.","Tavuk parçalarını çıkarıp kağıt havluyla kurulayın. Sosu tencerede kısık ateşte yarıya inene kadar 10 dakika kaynatın.","Geniş tavada 2 yemek kaşığı yağı kızdırın. Tavuk parçalarını deri tarafı aşağıya koyup 3-4 dakika, çıtır kahverengi olana kadar kızartın. Çevirin, 2 dakika daha.","İndirgenmiş sosu pişmiş tavukların üzerine gezdirin — sos yapışkan ve parlak olmalı.","Sıcak beyaz pirinç pilavı üzerine tavukları dizin, kalan sosu üstüne dökerek servis edin."',
"iran": '"Kuzu kıymayı rendelenmiş soğan, tuz ve karabiberle 5 dakika yoğurun. Yassı metal şişlere 15cm uzunluğunda, 2cm genişliğinde sıkıca sarın.","Basmati pirincini bol soğuk suda 3 kez yıkayıp 1 saat ıslatın. Süzün.","Kaynar tuzlu suda pirinci 6-7 dakika, tam al dente olana kadar haşlayın. Süzün.","Tencerenin dibine 2 yemek kaşığı yağ ve 1 yemek kaşığı su koyun. Pirinci üst üste gevşekçe yığın. Safranı sıcak suyla karıştırıp tepesine dökün. Kapağı havluyla sarıp kısık ateşte 45 dakika pişirin — altta çıtır tahdig oluşacak.","Şişleri kömür ateşinde veya çok kızgın ızgarada sık çevirerek 10-12 dakika pişirin.","Pilav tepesini bir tabağa ters çevirin — altın sarısı tahdig üstte kalmalı. Kebapları yanına koyun, üzerine sumak serpin ve ızgara domates ile servis edin."',
}
with open("Models/CountryData.swift") as f:
    content = f.read()
updated = 0
for cid, new_steps in steps.items():
    pattern = rf'(id: "{cid}".*?steps: \[)\s*\n\s*[^\]]*(\])'
    def replacer(m, ns=new_steps):
        return m.group(1) + "\n                " + ns + "\n            " + m.group(2)
    new_content = re.sub(pattern, replacer, content, flags=re.DOTALL, count=1)
    if new_content != content:
        updated += 1
        content = new_content
with open("Models/CountryData.swift", "w") as f:
    f.write(content)
print(f"Batch 2: Updated {updated} countries")
